import { InvalidReferenceError, InvalidStateError, LedgerIntegrityError, NotFoundError } from './errors.js';
import type { FinancialStatementRow, JournalEntry, JournalLine, StudentAttempt } from './model.js';
import type { ArAgingDetail, BankDeposit, CustomerBalance, CustomerPayment, InvoiceDetail, OperationalAttempt, OperationalCustomer, OperationalInvoice, OperationalTemplateCustomer, PaymentApplication, Reconciliation, ReconciliationResult, RegisterRow, ReportBasis, ReportPeriod } from './operations-model.js';
import { assertBalanced, profitAndLoss, type IdClock, type PostLine } from './service.js';

export interface OperationalStore { findForStudent(attemptId: string, studentId: string): Promise<OperationalAttempt | null>; save(state: OperationalAttempt): Promise<void> }
const amount = (value:number) => { if(!Number.isSafeInteger(value)||value<=0) throw new LedgerIntegrityError('Amount must be positive integer cents'); return value; };
const total = (values:readonly number[]) => values.reduce((sum,value)=>sum+value,0);

function nextAction(attempt:StudentAttempt, kind:StudentAttempt['actions'][number]['kind'], at:string, detail:Readonly<Record<string,unknown>>) { return { sequence:attempt.actions.length+1,kind,at,detail }; }
function makeEntry(attempt:StudentAttempt, system:IdClock, occurredOn:string, description:string, source:{kind:string,id:string}, input:readonly PostLine[]):JournalEntry {
  assertBalanced(input); const id=system.id(); const lines:JournalLine[]=input.map(line=>({id:system.id(),entryId:id,attemptAccountId:line.attemptAccountId,debitCents:line.debitCents??0,creditCents:line.creditCents??0}));
  return {id,attemptId:attempt.id,description,occurredOn,source,lines};
}
function withEntry(state:OperationalAttempt, entry:JournalEntry, action:StudentAttempt['actions'][number]):OperationalAttempt { return {...state,attempt:{...state.attempt,entries:[...state.attempt.entries,entry],actions:[...state.attempt.actions,action]}}; }
const invoiceAmount=(invoice:OperationalInvoice)=>total(invoice.lineItems.map(line=>line.amountCents));
const appliedToInvoice=(state:OperationalAttempt,id:string)=>total(state.applications.filter(a=>a.invoiceId===id).map(a=>a.amountCents));
const appliedFromPayment=(state:OperationalAttempt,id:string)=>total(state.applications.filter(a=>a.paymentId===id).map(a=>a.amountCents));

export class OperationalAccountingService {
  constructor(private readonly store:OperationalStore,private readonly system:IdClock){}
  private async own(studentId:string,attemptId:string){const state=await this.store.findForStudent(attemptId,studentId);if(!state)throw new NotFoundError('Attempt not found');if(state.attempt.status!=='ACTIVE')throw new InvalidStateError('Attempt is not writable');return state;}
  private account(state:OperationalAttempt,id:string){const account=state.attempt.accounts.find(a=>a.id===id);if(!account)throw new InvalidReferenceError('Account is outside this attempt');return account;}
  async createCustomer(studentId:string,attemptId:string,input:{name:string;sourceTemplateCustomerId?:string}):Promise<OperationalCustomer>{const state=await this.own(studentId,attemptId);const customer={id:this.system.id(),attemptId,name:input.name,active:true,sourceTemplateCustomerId:input.sourceTemplateCustomerId};await this.store.save({...state,customers:[...state.customers,customer],attempt:{...state.attempt,actions:[...state.attempt.actions,nextAction(state.attempt,'CUSTOMER_CREATED',this.system.now(),{customerId:customer.id})]}});return customer;}
  async postInvoice(studentId:string,attemptId:string,input:{customerId:string;number:string;invoiceDate:string;dueDate:string;arAccountId:string;lines:readonly {revenueAccountId:string;description:string;amountCents:number}[]}):Promise<OperationalInvoice>{
    let state=await this.own(studentId,attemptId);if(!state.customers.some(c=>c.id===input.customerId&&c.active))throw new InvalidReferenceError('Customer unavailable');this.account(state,input.arAccountId);if(!input.lines.length)throw new LedgerIntegrityError('Invoice requires at least one line');input.lines.forEach(line=>{amount(line.amountCents);this.account(state,line.revenueAccountId)});
    const id=this.system.id(), lines=input.lines.map(line=>({id:this.system.id(),...line})), gross=total(lines.map(line=>line.amountCents));const entry=makeEntry(state.attempt,this.system,input.invoiceDate,`Invoice ${input.number}`,{kind:'INVOICE',id},[{attemptAccountId:input.arAccountId,debitCents:gross},...lines.map(line=>({attemptAccountId:line.revenueAccountId,creditCents:line.amountCents}))]);
    const invoice:OperationalInvoice={id,attemptId,customerId:input.customerId,number:input.number,invoiceDate:input.invoiceDate,dueDate:input.dueDate,status:'OPEN',arAccountId:input.arAccountId,lineItems:lines,journalEntryId:entry.id};state=withEntry({...state,invoices:[...state.invoices,invoice]},entry,nextAction(state.attempt,'INVOICE_POSTED',this.system.now(),{invoiceId:id}));await this.store.save(state);return invoice;
  }
  async receivePayment(studentId:string,attemptId:string,input:{customerId:string;paymentDate:string;amountCents:number;destinationAccountId:string;arAccountId:string;method?:string;reference?:string}):Promise<CustomerPayment>{
    let state=await this.own(studentId,attemptId);if(!state.customers.some(c=>c.id===input.customerId))throw new InvalidReferenceError('Customer unavailable');amount(input.amountCents);this.account(state,input.destinationAccountId);this.account(state,input.arAccountId);const id=this.system.id();const entry=makeEntry(state.attempt,this.system,input.paymentDate,'Customer payment',{kind:'CUSTOMER_PAYMENT',id},[{attemptAccountId:input.destinationAccountId,debitCents:input.amountCents},{attemptAccountId:input.arAccountId,creditCents:input.amountCents}]);const payment:CustomerPayment={id,attemptId,customerId:input.customerId,paymentDate:input.paymentDate,amountCents:input.amountCents,destinationAccountId:input.destinationAccountId,method:input.method,reference:input.reference,journalEntryId:entry.id};state=withEntry({...state,payments:[...state.payments,payment]},entry,nextAction(state.attempt,'PAYMENT_RECEIVED',this.system.now(),{paymentId:id}));await this.store.save(state);return payment;
  }
  async applyPayment(studentId:string,attemptId:string,paymentId:string,invoiceId:string,value:number):Promise<PaymentApplication>{
    const state=await this.own(studentId,attemptId),payment=state.payments.find(p=>p.id===paymentId),invoice=state.invoices.find(i=>i.id===invoiceId);if(!payment||!invoice)throw new InvalidReferenceError('Payment or invoice unavailable');if(payment.customerId!==invoice.customerId)throw new InvalidReferenceError('Payment or invoice unavailable');amount(value);if(appliedFromPayment(state,paymentId)+value>payment.amountCents||appliedToInvoice(state,invoiceId)+value>invoiceAmount(invoice))throw new InvalidStateError('Application exceeds available balance');const application={id:this.system.id(),attemptId,paymentId,invoiceId,amountCents:value,appliedAt:this.system.now()};const applications=[...state.applications,application];const paid=appliedToInvoice({...state,applications},invoiceId)===invoiceAmount(invoice);await this.store.save({...state,applications,invoices:state.invoices.map(i=>i.id===invoiceId?{...i,status:paid?'PAID':'OPEN'}:i),attempt:{...state.attempt,actions:[...state.attempt.actions,nextAction(state.attempt,'PAYMENT_APPLIED',this.system.now(),{applicationId:application.id})]}});return application;
  }
  async createDeposit(studentId:string,attemptId:string,input:{depositDate:string;bankAccountId:string;undepositedFundsAccountId:string;paymentIds:readonly string[]}):Promise<BankDeposit>{
    let state=await this.own(studentId,attemptId);this.account(state,input.bankAccountId);this.account(state,input.undepositedFundsAccountId);if(!input.paymentIds.length||new Set(input.paymentIds).size!==input.paymentIds.length)throw new InvalidReferenceError('Payments are not depositable');const already=new Set(state.deposits.flatMap(d=>d.paymentIds));const payments=input.paymentIds.map(id=>state.payments.find(p=>p.id===id)).filter((p):p is CustomerPayment=>Boolean(p));if(payments.length!==input.paymentIds.length||payments.some(p=>p.destinationAccountId!==input.undepositedFundsAccountId||already.has(p.id)))throw new InvalidReferenceError('Payments are not depositable');const value=total(payments.map(p=>p.amountCents)),id=this.system.id();const entry=makeEntry(state.attempt,this.system,input.depositDate,'Bank deposit',{kind:'BANK_DEPOSIT',id},[{attemptAccountId:input.bankAccountId,debitCents:value},{attemptAccountId:input.undepositedFundsAccountId,creditCents:value}]);const deposit={id,attemptId,depositDate:input.depositDate,bankAccountId:input.bankAccountId,paymentIds:[...input.paymentIds],amountCents:value,journalEntryId:entry.id};state=withEntry({...state,deposits:[...state.deposits,deposit]},entry,nextAction(state.attempt,'BANK_DEPOSIT_POSTED',this.system.now(),{depositId:id}));await this.store.save(state);return deposit;
  }
  async recordCardPurchase(studentId:string,attemptId:string,input:{date:string;cardAccountId:string;purchaseAccountId:string;amountCents:number}):Promise<JournalEntry>{let state=await this.own(studentId,attemptId);this.account(state,input.cardAccountId);this.account(state,input.purchaseAccountId);amount(input.amountCents);const id=this.system.id(),entry=makeEntry(state.attempt,this.system,input.date,'Credit-card purchase',{kind:'CARD_PURCHASE',id},[{attemptAccountId:input.purchaseAccountId,debitCents:input.amountCents},{attemptAccountId:input.cardAccountId,creditCents:input.amountCents}]);state=withEntry(state,entry,nextAction(state.attempt,'CARD_PURCHASE_POSTED',this.system.now(),{entryId:entry.id}));await this.store.save(state);return entry;}
  async payCreditCard(studentId:string,attemptId:string,input:{date:string;bankAccountId:string;cardAccountId:string;amountCents:number}):Promise<JournalEntry>{let state=await this.own(studentId,attemptId);this.account(state,input.bankAccountId);this.account(state,input.cardAccountId);amount(input.amountCents);const id=this.system.id(),entry=makeEntry(state.attempt,this.system,input.date,'Credit-card payment',{kind:'CARD_PAYMENT',id},[{attemptAccountId:input.cardAccountId,debitCents:input.amountCents},{attemptAccountId:input.bankAccountId,creditCents:input.amountCents}]);state=withEntry(state,entry,nextAction(state.attempt,'CARD_PAYMENT_POSTED',this.system.now(),{entryId:entry.id}));await this.store.save(state);return entry;}
  async startReconciliation(studentId:string,attemptId:string,input:{accountId:string;beginningDate:string;endingDate:string;beginningBalanceCents:number;endingBalanceCents:number;clearedJournalLineIds:readonly string[]}):Promise<Reconciliation>{const state=await this.own(studentId,attemptId),account=this.account(state,input.accountId);if(!['ASSET','LIABILITY'].includes(account.kind))throw new InvalidReferenceError('Account is not reconcilable');const lines=state.attempt.entries.flatMap(e=>e.lines).filter(l=>input.clearedJournalLineIds.includes(l.id));if(lines.length!==new Set(input.clearedJournalLineIds).size||lines.some(l=>l.attemptAccountId!==input.accountId))throw new InvalidReferenceError('Cleared lines are unavailable');const fingerprints=Object.fromEntries(lines.map(l=>[l.id,`${l.debitCents}:${l.creditCents}:${l.attemptAccountId}`]));const reconciliation={id:this.system.id(),attemptId,accountId:input.accountId,beginningDate:input.beginningDate,endingDate:input.endingDate,beginningBalanceCents:input.beginningBalanceCents,endingBalanceCents:input.endingBalanceCents,clearedJournalLineIds:[...input.clearedJournalLineIds],clearedLineFingerprints:fingerprints,status:'IN_PROGRESS' as const};await this.store.save({...state,reconciliations:[...state.reconciliations,reconciliation],attempt:{...state.attempt,actions:[...state.attempt.actions,nextAction(state.attempt,'RECONCILIATION_STARTED',this.system.now(),{reconciliationId:reconciliation.id})]}});return reconciliation;}
  async completeReconciliation(studentId:string,attemptId:string,id:string):Promise<Reconciliation>{const state=await this.own(studentId,attemptId),reconciliation=state.reconciliations.find(r=>r.id===id);if(!reconciliation)throw new InvalidReferenceError('Reconciliation unavailable');const result=reconciliationResult(state,reconciliation);if(!result.balanced||!result.historicalIntegrity)throw new InvalidStateError('Reconciliation is not balanced');const completed={...reconciliation,status:'COMPLETED' as const,completedAt:this.system.now()};await this.store.save({...state,reconciliations:state.reconciliations.map(r=>r.id===id?completed:r),attempt:{...state.attempt,actions:[...state.attempt.actions,nextAction(state.attempt,'RECONCILIATION_COMPLETED',this.system.now(),{reconciliationId:id})]}});return completed;}
}

export function invoiceDetails(state:OperationalAttempt):InvoiceDetail[]{return state.invoices.map(invoice=>{const gross=invoiceAmount(invoice),applied=appliedToInvoice(state,invoice.id);return{invoiceId:invoice.id,customerId:invoice.customerId,invoiceDate:invoice.invoiceDate,dueDate:invoice.dueDate,amountCents:gross,appliedCents:applied,openCents:gross-applied}});}
export function arAging(state:OperationalAttempt,asOf:string):ArAgingDetail[]{const asOfTime=new Date(`${asOf}T00:00:00Z`).getTime();return invoiceDetails(state).filter(invoice=>invoice.openCents!==0).map(invoice=>({...invoice,daysPastDue:Math.max(0,Math.floor((asOfTime-new Date(`${invoice.dueDate}T00:00:00Z`).getTime())/86400000))}));}
export function customerBalances(state:OperationalAttempt):CustomerBalance[]{return state.customers.map(customer=>{const invoiceOpenCents=total(invoiceDetails(state).filter(i=>i.customerId===customer.id).map(i=>i.openCents)),unappliedPaymentCents=total(state.payments.filter(p=>p.customerId===customer.id).map(p=>p.amountCents-appliedFromPayment(state,p.id)));return{customerId:customer.id,invoiceOpenCents,unappliedPaymentCents,netReceivableCents:invoiceOpenCents-unappliedPaymentCents}});}
export function arControlDifference(state:OperationalAttempt,arAccountId:string):number{const row=state.attempt.accounts.find(a=>a.id===arAccountId);if(!row)throw new InvalidReferenceError('Account is outside this attempt');let ledger=0;for(const entry of state.attempt.entries)for(const line of entry.lines)if(line.attemptAccountId===arAccountId)ledger+=line.debitCents-line.creditCents;return ledger-total(customerBalances(state).map(c=>c.netReceivableCents));}
export function operationalProfitAndLoss(state:OperationalAttempt,basis:ReportBasis,period?:ReportPeriod){const inPeriod=(date:string)=>!period||(date>=period.from&&date<=period.through);const periodAttempt={...state.attempt,entries:state.attempt.entries.filter(entry=>inPeriod(entry.occurredOn))};if(basis==='ACCRUAL')return profitAndLoss(periodAttempt);const base=profitAndLoss({...periodAttempt,entries:periodAttempt.entries.filter(e=>e.source?.kind!=='INVOICE')});const byAccount=new Map<string,number>();for(const application of state.applications){const payment=state.payments.find(p=>p.id===application.paymentId)!;if(!inPeriod(payment.paymentDate))continue;const invoice=state.invoices.find(i=>i.id===application.invoiceId)!;let remaining=application.amountCents;invoice.lineItems.forEach((line,index)=>{const recognized=index===invoice.lineItems.length-1?remaining:Math.floor(application.amountCents*line.amountCents/invoiceAmount(invoice));remaining-=recognized;byAccount.set(line.revenueAccountId,(byAccount.get(line.revenueAccountId)??0)+recognized);});}const revenue:FinancialStatementRow[]=state.attempt.accounts.filter(a=>a.kind==='REVENUE').map(a=>({accountId:a.id,code:a.code,name:a.name,amountCents:byAccount.get(a.id)??0}));return{revenue,expenses:base.expenses,netIncomeCents:total(revenue.map(r=>r.amountCents))-total(base.expenses.map(r=>r.amountCents))};}
export function accountRegister(state:OperationalAttempt,accountId:string):RegisterRow[]{let running=0;return state.attempt.entries.flatMap(entry=>entry.lines.filter(line=>line.attemptAccountId===accountId).map(line=>{running+=line.debitCents-line.creditCents;return{entry,lineId:line.id,debitCents:line.debitCents,creditCents:line.creditCents,runningBalanceCents:running}}));}
export function reconciliationResult(state:OperationalAttempt,reconciliation:Reconciliation):ReconciliationResult{const account=state.attempt.accounts.find(a=>a.id===reconciliation.accountId);if(!account)throw new InvalidReferenceError('Account is outside this attempt');const lines=state.attempt.entries.flatMap(e=>e.lines).filter(l=>reconciliation.clearedJournalLineIds.includes(l.id));const historicalIntegrity=lines.length===reconciliation.clearedJournalLineIds.length&&lines.every(l=>reconciliation.clearedLineFingerprints[l.id]===`${l.debitCents}:${l.creditCents}:${l.attemptAccountId}`);const movement=total(lines.map(l=>account.kind==='LIABILITY'?l.creditCents-l.debitCents:l.debitCents-l.creditCents));const calculatedClearedBalanceCents=reconciliation.beginningBalanceCents+movement,differenceCents=reconciliation.endingBalanceCents-calculatedClearedBalanceCents;return{calculatedClearedBalanceCents,differenceCents,balanced:differenceCents===0,historicalIntegrity};}
export function operationalStudentView(state:OperationalAttempt){return{attemptId:state.attempt.id,customers:state.customers.map(customer=>({id:customer.id,attemptId:customer.attemptId,name:customer.name,active:customer.active})),invoices:invoiceDetails(state),payments:state.payments.map(payment=>({id:payment.id,attemptId:payment.attemptId,customerId:payment.customerId,paymentDate:payment.paymentDate,amountCents:payment.amountCents,destinationAccountId:payment.destinationAccountId,method:payment.method,reference:payment.reference,journalEntryId:payment.journalEntryId})),applications:state.applications,deposits:state.deposits,reconciliations:state.reconciliations.map(reconciliation=>({id:reconciliation.id,attemptId:reconciliation.attemptId,accountId:reconciliation.accountId,beginningDate:reconciliation.beginningDate,endingDate:reconciliation.endingDate,beginningBalanceCents:reconciliation.beginningBalanceCents,endingBalanceCents:reconciliation.endingBalanceCents,clearedJournalLineIds:reconciliation.clearedJournalLineIds,status:reconciliation.status,completedAt:reconciliation.completedAt}))};}
export function initializeOperationalAttempt(attempt:StudentAttempt,templateCustomers:readonly OperationalTemplateCustomer[],system:IdClock):OperationalAttempt{return{attempt,customers:templateCustomers.map(customer=>({id:system.id(),attemptId:attempt.id,sourceTemplateCustomerId:customer.id,name:customer.name,active:customer.active})),invoices:[],payments:[],applications:[],deposits:[],reconciliations:[]};}
