import type { AttemptAccount, JournalEntry, StudentAttempt } from './model.js';
import type { OperationalAttempt, PaymentApplication, Reconciliation } from './operations-model.js';
import { arControlDifference, customerBalances, invoiceDetails, operationalProfitAndLoss, operationalStudentView, reconciliationResult } from './operations.js';
import { balanceSheet, studentView, trialBalance } from './service.js';
import { buildSuncoastMasterCase, suncoastAuthoritativeStatements, type SuncoastMasterCase } from './suncoast-master.js';

export type P002ScenarioClass='STARTING_ERROR'|'INVESTIGATION_CONTROL'|'PROFESSIONAL_JUDGMENT_CONTROL'|'UNRESOLVED_INFORMATION'|'RECONCILIATION_CONSEQUENCE';
export type P002ActionKind='TRANSACTION_REVIEWED'|'CONTROL_VERIFIED'|'ACCOUNT_CHANGED'|'TRANSACTION_CORRECTED'|'TRANSACTION_VOIDED'|'APPLICATION_CHANGED'|'DOCUMENT_REVIEWED'|'ISSUE_FLAGGED'|'HISTORICAL_TRANSACTION_ALTERED'|'RECONCILIATION_ACTIVITY'|'RECONCILIATION_ADJUSTMENT_ATTEMPTED'|'ACCOUNT_CONSOLIDATED'|'SELF_CORRECTION';

interface ScenarioDefinition {readonly id:`SUN-L1-${string}`;readonly classification:P002ScenarioClass;readonly title:string;readonly cleanTruth:string;readonly startingCondition:string;readonly accountingEffect:string;readonly availableEvidence:readonly string[];readonly unavailableEvidence:readonly string[];readonly investigationPath:string;readonly validResolution:string;readonly criticalActions:readonly string[]}
export interface P002AuditEvent {readonly sequence:number;readonly at:string;readonly action:P002ActionKind;readonly targetId:string;readonly hook?:string;readonly verifiedCorrect?:boolean;readonly selfCorrected?:boolean;readonly helpLevel?:'HINT'|'DIRECTION'|'WALKTHROUGH';readonly commandId?:string;readonly revision?:number;readonly note?:string;readonly visibleDocumentIds?:readonly string[];readonly before?:unknown;readonly after?:unknown}
interface ScenarioProvenance {readonly scenarioId:ScenarioDefinition['id'];readonly cleanRecordIds:readonly string[];readonly studentRecordIds:readonly string[];readonly transformation:string}
export interface P002StudentStart {readonly state:OperationalAttempt;readonly visibleDocuments:readonly {id:string;title:string;date:string;counterparty:string;available:boolean}[];readonly auditTrail:readonly P002AuditEvent[]}
export interface P002InstructorState {readonly attempt:P002StudentStart;readonly scenarios:readonly ScenarioDefinition[];readonly provenance:readonly ScenarioProvenance[];readonly hiddenFacts:Readonly<Record<string,string>>;readonly criticalHooks:Readonly<Record<string,string>>;readonly authoritativeStatements:{readonly checkingEndingBalanceCents:number;readonly visaEndingBalanceCents:number};readonly cleanMaster:SuncoastMasterCase}

export const p002ScenarioDefinitions:readonly ScenarioDefinition[]=Object.freeze([
  {id:'SUN-L1-01',classification:'STARTING_ERROR',title:'Actual duplicate expense',cleanTruth:'One supported June 25 Sherwin-Williams purchase for $487.36.',startingCondition:'A second unsupported card purchase is present.',accountingEffect:'Materials expense and Visa are overstated $487.36.',availableEvidence:['bank/card activity','neutral vendor support metadata'],unavailableEvidence:[],investigationPath:'Compare source identity and retain the supported purchase.',validResolution:'Void only the unsupported duplicate with history retained.',criticalActions:[]},
  {id:'SUN-L1-02',classification:'INVESTIGATION_CONTROL',title:'Legitimate twin purchases',cleanTruth:'Two distinct June 22 Home Depot purchases of $642.18 support Jenkins and Palm Breeze.',startingCondition:'Both legitimate purchases remain.',accountingEffect:'None.',availableEvidence:['two distinct source records'],unavailableEvidence:[],investigationPath:'Verify provenance before changing either item.',validResolution:'Retain both.',criticalActions:['deleting either supported purchase']},
  {id:'SUN-L1-03',classification:'STARTING_ERROR',title:'Owner contribution in income',cleanTruth:'The May 4 $5,000 deposit credits Owner Contributions.',startingCondition:'The deposit credits Painting Income.',accountingEffect:'Revenue and current earnings are overstated; contributed equity is understated.',availableEvidence:['bank deposit','owner transaction metadata'],unavailableEvidence:[],investigationPath:'Determine whether the receipt is earned revenue or capital.',validResolution:'Reclassify the credit to Owner Contributions without changing cash.',criticalActions:[]},
  {id:'SUN-L1-04',classification:'STARTING_ERROR',title:'Loan payment fully expensed',cleanTruth:'The $925 payment is $690 principal and $235 interest.',startingCondition:'The full payment is Vehicle Expense.',accountingEffect:'Expense is overstated $690 and loan liability is overstated $690.',availableEvidence:['payment activity','loan support'],unavailableEvidence:[],investigationPath:'Use lender support to split principal and interest.',validResolution:'Debit Vehicle Loan Payable $690 and Interest Expense $235.',criticalActions:[]},
  {id:'SUN-L1-05',classification:'STARTING_ERROR',title:'Pressure washer expensed',cleanTruth:'The June 8 $6,800 pressure washer is Tools & Equipment.',startingCondition:'It is Repairs & Maintenance expense.',accountingEffect:'Assets are understated and expenses overstated $6,800.',availableEvidence:['vendor support'],unavailableEvidence:[],investigationPath:'Inspect the nature and expected use of the purchase.',validResolution:'Restore Tools & Equipment; depreciation remains out of scope.',criticalActions:[]},
  {id:'SUN-L1-06',classification:'UNRESOLVED_INFORMATION',title:'ABC transaction unresolved',cleanTruth:'The June 17 $2,400 payment is a trailer deposit asset.',startingCondition:'It is held in an attempt-only suspense asset.',accountingEffect:'Total assets are correct but classification is unresolved.',availableEvidence:['bank transaction'],unavailableEvidence:['trailer purpose'],investigationPath:'Flag and request client support rather than guess.',validResolution:'Leave unresolved until support permits Trailer Deposit classification.',criticalActions:['unsupported classification guess']},
  {id:'SUN-L1-07',classification:'STARTING_ERROR',title:'Martinez receipt duplicated',cleanTruth:'Invoice, payment, Undeposited Funds, and bank deposit form one lifecycle.',startingCondition:'The deposit link is absent and bank activity is separately credited to income.',accountingEffect:'Revenue and Undeposited Funds are each overstated $3,850.',availableEvidence:['invoice','receipt','bank activity'],unavailableEvidence:[],investigationPath:'Trace the receipt through Undeposited Funds to the bank.',validResolution:'Restore the deposit linkage and remove only the duplicate income effect.',criticalActions:[]},
  {id:'SUN-L1-08',classification:'STARTING_ERROR',title:'Reynolds application wrong',cleanTruth:'The $1,850 payment applies to Invoice A.',startingCondition:'It is applied to Invoice B.',accountingEffect:'Customer total is unchanged but invoice detail is wrong.',availableEvidence:['payment reference','two invoices'],unavailableEvidence:[],investigationPath:'Match the payment to supported invoice identity.',validResolution:'Move the application to Invoice A.',criticalActions:[]},
  {id:'SUN-L1-09',classification:'INVESTIGATION_CONTROL',title:'Jenkins old invoice',cleanTruth:'The $1,425 receivable is valid and collectible.',startingCondition:'It remains open.',accountingEffect:'None.',availableEvidence:['invoice and aging'],unavailableEvidence:['collectibility conclusion'],investigationPath:'Investigate rather than delete or write off.',validResolution:'Leave outstanding absent contrary support.',criticalActions:['delete or unsupported write-off']},
  {id:'SUN-L1-10',classification:'PROFESSIONAL_JUDGMENT_CONTROL',title:'Historical CPA entry',cleanTruth:'The December 31 CPA accrual is legitimate.',startingCondition:'It remains unchanged.',accountingEffect:'None.',availableEvidence:['historical journal'],unavailableEvidence:['protected CPA explanation'],investigationPath:'Review history and avoid unsupported changes.',validResolution:'Retain the entry.',criticalActions:['unsupported alteration']},
  {id:'SUN-L1-11',classification:'STARTING_ERROR',title:'Added instead of matched',cleanTruth:'The June rent transaction already records the bank activity.',startingCondition:'A second bank-side rent expense was added.',accountingEffect:'Rent expense and checking withdrawals are overstated $2,500.',availableEvidence:['bank activity','existing transaction'],unavailableEvidence:[],investigationPath:'Match the activity to the existing source transaction.',validResolution:'Remove only the unsupported added duplicate.',criticalActions:[]},
  {id:'SUN-L1-12',classification:'STARTING_ERROR',title:'Transfer recorded as expense',cleanTruth:'A $5,550 customer deposit moves Undeposited Funds to checking.',startingCondition:'The movement debits Advertising expense instead of checking.',accountingEffect:'Checking is understated and expense overstated $5,550.',availableEvidence:['deposit record','bank activity'],unavailableEvidence:[],investigationPath:'Trace the balance-sheet movement.',validResolution:'Restore the debit to Operating Checking.',criticalActions:[]},
  {id:'SUN-L1-13',classification:'STARTING_ERROR',title:'Reconciled transaction altered',cleanTruth:'The June Office Depot transaction is $318.',startingCondition:'The reconciled entry is altered to $381.',accountingEffect:'Expense/checking differ $63 and historical fingerprint fails.',availableEvidence:['reconciliation history','transaction history'],unavailableEvidence:[],investigationPath:'Inspect historical reconciliation changes.',validResolution:'Restore the supported $318 entry.',criticalActions:['forced reconciliation adjustment']},
  {id:'SUN-L1-14',classification:'UNRESOLVED_INFORMATION',title:'Personal card activity',cleanTruth:'A new $286.43 Visa purchase is personal and ultimately belongs in Owner Draws.',startingCondition:'It is held in suspense pending clarification.',accountingEffect:'Visa is correct; classification is unresolved.',availableEvidence:['card activity'],unavailableEvidence:['personal purpose'],investigationPath:'Flag and seek client clarification.',validResolution:'After facts become available, classify to Owner Draws.',criticalActions:['unsupported treatment after facts known']},
  {id:'SUN-L1-15',classification:'STARTING_ERROR',title:'Card payment expensed',cleanTruth:'The $3,500 payment decreases checking and Visa liability.',startingCondition:'It debits Bank Fees instead of Visa.',accountingEffect:'Expense and Visa liability are overstated $3,500.',availableEvidence:['checking and Visa activity'],unavailableEvidence:[],investigationPath:'Match both sides of the balance-sheet transfer.',validResolution:'Restore debit to Visa.',criticalActions:[]},
  {id:'SUN-L1-16',classification:'STARTING_ERROR',title:'Payroll withdrawal simplified',cleanTruth:'Protected provider components support wages, employer tax, liabilities, remittance, net pay, and fee.',startingCondition:'All three withdrawals are collapsed to Payroll Expense.',accountingEffect:'Payroll categories and liability lifecycle are wrong; total cash remains correct.',availableEvidence:['three bank withdrawals'],unavailableEvidence:['payroll component report'],investigationPath:'Obtain and compare the later provider report.',validResolution:'Restore the P-001A payroll journals.',criticalActions:[]},
  {id:'SUN-L1-17',classification:'PROFESSIONAL_JUDGMENT_CONTROL',title:'Messy chart',cleanTruth:'The clean chart has one Advertising & Marketing account.',startingCondition:'Four redundant attempt-only expense accounts exist.',accountingEffect:'No starting financial effect.',availableEvidence:['attempt chart'],unavailableEvidence:[],investigationPath:'Evaluate consolidation without losing history.',validResolution:'Consolidate safely with an auditable mapping.',criticalActions:[]},
  {id:'SUN-L1-18',classification:'UNRESOLVED_INFORMATION',title:'Legitimate unapplied amount',cleanTruth:'A new $750 customer payment is intended for a future job.',startingCondition:'The payment is legitimately unapplied.',accountingEffect:'Checking increases, A/R control remains aligned, and customer net receivable decreases.',availableEvidence:['receipt and bank activity'],unavailableEvidence:['future-job intention'],investigationPath:'Leave unapplied and request clarification.',validResolution:'Retain unresolved until instructed.',criticalActions:['arbitrary apply, refund, deletion, or removal']},
  {id:'SUN-L1-19',classification:'INVESTIGATION_CONTROL',title:'Palm Breeze receipt',cleanTruth:'The $9,500 receipt is legitimate.',startingCondition:'It remains unchanged.',accountingEffect:'None.',availableEvidence:['invoice','receipt','deposit'],unavailableEvidence:[],investigationPath:'Verify the complete lifecycle.',validResolution:'Retain it.',criticalActions:['unsupported removal']},
  {id:'SUN-L1-20',classification:'RECONCILIATION_CONSEQUENCE',title:'Final reconciliation consequence',cleanTruth:'Supported activity reconciles without adjustment.',startingCondition:'Controlled errors create natural reconciliation and historical-integrity problems.',accountingEffect:'Checking/Visa reconciliation cannot complete cleanly.',availableEvidence:['register','statements','reconciliation history'],unavailableEvidence:['scenario inventory'],investigationPath:'Correct underlying bookkeeping.',validResolution:'Reach zero without a plug.',criticalActions:['forced reconciliation adjustment']},
]);

const hiddenFacts=Object.freeze({trailerPurpose:'The ABC payment is a deposit toward an enclosed work trailer.',personalCardPurpose:'The $286.43 Visa purchase is personal and should be Owner Draws after clarification.',unappliedPurpose:'The customer intends the $750 payment for a future job.',payrollSupport:'The protected P-001A provider component report is unavailable at start.'});
const criticalHooks=Object.freeze({HOME_DEPOT_SUPPORTED_REMOVED:'SUN-L1-02',CPA_HISTORY_ALTERED:'SUN-L1-10',ABC_CLASSIFICATION_GUESSED:'SUN-L1-06',JENKINS_RECEIVABLE_REMOVED:'SUN-L1-09',UNAPPLIED_AMOUNT_DISPOSED:'SUN-L1-18',RECONCILIATION_ADJUSTMENT_FORCED:'SUN-L1-20',PALM_BREEZE_RECEIPT_REMOVED:'SUN-L1-19',PERSONAL_CARD_UNSUPPORTED_TREATMENT:'SUN-L1-14'});
export type P002CriticalHook=keyof typeof criticalHooks;

function cloneMaster(master:SuncoastMasterCase,studentId:string,attemptId:string,generation:number):OperationalAttempt{
  const state=structuredClone(master.state);const accountMap=new Map(state.attempt.accounts.map((account,index)=>[account.id,`${attemptId}-account-${String(index+1).padStart(3,'0')}`]));const entryMap=new Map(state.attempt.entries.map((entry,index)=>[entry.id,`${attemptId}-entry-${String(index+1).padStart(3,'0')}`]));const lineMap=new Map(state.attempt.entries.flatMap(entry=>entry.lines).map((line,index)=>[line.id,`${attemptId}-line-${String(index+1).padStart(4,'0')}`]));const customerMap=new Map(state.customers.map((customer,index)=>[customer.id,`${attemptId}-customer-${String(index+1).padStart(2,'0')}`]));const invoiceMap=new Map(state.invoices.map((invoice,index)=>[invoice.id,`${attemptId}-invoice-${String(index+1).padStart(2,'0')}`]));const paymentMap=new Map(state.payments.map((payment,index)=>[payment.id,`${attemptId}-payment-${String(index+1).padStart(2,'0')}`]));
  const entries=state.attempt.entries.map(entry=>({...entry,id:entryMap.get(entry.id)!,attemptId,lines:entry.lines.map(line=>({...line,id:lineMap.get(line.id)!,entryId:entryMap.get(entry.id)!,attemptAccountId:accountMap.get(line.attemptAccountId)!}))}));
  const attempt:StudentAttempt={...state.attempt,id:attemptId,studentId,generation,status:'ACTIVE',accounts:state.attempt.accounts.map(account=>({...account,id:accountMap.get(account.id)!,attemptId})),entries,actions:[{sequence:1,kind:generation===1?'ATTEMPT_CREATED':'ATTEMPT_RESET',at:'2026-07-01T09:00:00.000Z',detail:generation===1?{}:{generation}}],unlockedDocumentIds:[]};
  return{attempt,customers:state.customers.map(customer=>({...customer,id:customerMap.get(customer.id)!,attemptId})),invoices:state.invoices.map(invoice=>({...invoice,id:invoiceMap.get(invoice.id)!,attemptId,customerId:customerMap.get(invoice.customerId)!,arAccountId:accountMap.get(invoice.arAccountId)!,journalEntryId:entryMap.get(invoice.journalEntryId)!,lineItems:invoice.lineItems.map(line=>({...line,revenueAccountId:accountMap.get(line.revenueAccountId)!}))})),payments:state.payments.map(payment=>({...payment,id:paymentMap.get(payment.id)!,attemptId,customerId:customerMap.get(payment.customerId)!,destinationAccountId:accountMap.get(payment.destinationAccountId)!,journalEntryId:entryMap.get(payment.journalEntryId)!})),applications:state.applications.map(application=>({...application,id:`${attemptId}-application-${application.id}`,attemptId,paymentId:paymentMap.get(application.paymentId)!,invoiceId:invoiceMap.get(application.invoiceId)!})),deposits:state.deposits.map(deposit=>({...deposit,id:`${attemptId}-deposit-${deposit.id}`,attemptId,bankAccountId:accountMap.get(deposit.bankAccountId)!,paymentIds:deposit.paymentIds.map(id=>paymentMap.get(id)!),journalEntryId:entryMap.get(deposit.journalEntryId)!})),reconciliations:state.reconciliations.map(reconciliation=>({...reconciliation,id:`${attemptId}-historical-${reconciliation.id}`,attemptId,accountId:accountMap.get(reconciliation.accountId)!,clearedJournalLineIds:reconciliation.clearedJournalLineIds.map(id=>lineMap.get(id)!),clearedLineFingerprints:Object.fromEntries(reconciliation.clearedJournalLineIds.map(id=>{const old=state.attempt.entries.flatMap(entry=>entry.lines).find(line=>line.id===id)!;const mapped=lineMap.get(id)!;return[mapped,`${old.debitCents}:${old.creditCents}:${accountMap.get(old.attemptAccountId)!}`]}))}))};
}

const accountId=(state:OperationalAttempt,name:string)=>{const id=state.attempt.accounts.find(account=>account.name===name)?.id;if(!id)throw new Error(`Missing account ${name}`);return id};
const replaceLines=(state:OperationalAttempt,entryId:string,lines:readonly {account:string;debitCents?:number;creditCents?:number}[])=>({...state,attempt:{...state.attempt,entries:state.attempt.entries.map(entry=>entry.id===entryId?{...entry,lines:lines.map((line,index)=>({id:index<entry.lines.length?entry.lines[index].id:`${entry.id}-extra-${index}`,entryId:entry.id,attemptAccountId:accountId(state,line.account),debitCents:line.debitCents??0,creditCents:line.creditCents??0}))}:entry)}});
const entryByDescription=(state:OperationalAttempt,text:string)=>{const entry=state.attempt.entries.find(value=>value.description===text);if(!entry)throw new Error(`Missing entry ${text}`);return entry};
const addEntry=(state:OperationalAttempt,id:string,date:string,description:string,sourceKind:string,lines:readonly {account:string;debitCents?:number;creditCents?:number}[])=>{const entry:JournalEntry={id,attemptId:state.attempt.id,occurredOn:date,description,source:{kind:sourceKind,id:`${id}-source`},lines:lines.map((line,index)=>({id:`${id}-line-${index+1}`,entryId:id,attemptAccountId:accountId(state,line.account),debitCents:line.debitCents??0,creditCents:line.creditCents??0}))};return{...state,attempt:{...state.attempt,entries:[...state.attempt.entries,entry]}}};

function addAttemptAccounts(state:OperationalAttempt):OperationalAttempt{const names=['Uncategorized / Ask My Accountant','Advertising','Advertising Expense','Marketing','Marketing & Advertising'];const accounts:AttemptAccount[]=names.map((name,index)=>({id:`${state.attempt.id}-p002-account-${index+1}`,attemptId:state.attempt.id,sourceTemplateAccountId:`attempt-only-${index+1}`,code:`P${String(index+1).padStart(3,'0')}`,name,kind:index===0?'ASSET':'EXPENSE'}));return{...state,attempt:{...state.attempt,accounts:[...state.attempt.accounts,...accounts]}}}

function addNewLegitimateActivity(state:OperationalAttempt,resolved=false):OperationalAttempt{
  state=addEntry(state,`${state.attempt.id}-card-review-0624`,'2026-06-24',resolved?'Card purchase clarified':'Card purchase pending client clarification','P002_CARD_ACTIVITY',[{account:resolved?'Owner Draws':'Uncategorized / Ask My Accountant',debitCents:28643},{account:'Gulf Coast Business Visa',creditCents:28643}]);
  const customer=state.customers.find(value=>value.name==='Cape Premier Realty')!;const paymentId=`${state.attempt.id}-future-payment`,entryId=`${state.attempt.id}-future-payment-entry`;state=addEntry(state,entryId,'2026-06-30','Customer payment','CUSTOMER_PAYMENT',[{account:'Operating Checking',debitCents:75000},{account:'Accounts Receivable',creditCents:75000}]);return{...state,payments:[...state.payments,{id:paymentId,attemptId:state.attempt.id,customerId:customer.id,paymentDate:'2026-06-30',amountCents:75000,destinationAccountId:accountId(state,'Operating Checking'),method:'ACH',reference:'CLIENT-ADVANCE-0630',journalEntryId:entryId}]};
}

function applyStartingErrors(input:OperationalAttempt):{state:OperationalAttempt;provenance:ScenarioProvenance[]}{let state=input;const provenance:ScenarioProvenance[]=[];const track=(scenarioId:ScenarioDefinition['id'],cleanRecordIds:readonly string[],studentRecordIds:readonly string[],transformation:string)=>provenance.push({scenarioId,cleanRecordIds,studentRecordIds,transformation});
  const sherwin=state.attempt.entries.find(entry=>entry.occurredOn==='2026-06-25'&&entry.source?.kind==='CARD_PURCHASE')!;state=addEntry(state,`${state.attempt.id}-unsupported-sherwin`,'2026-06-25','Sherwin-Williams card purchase','P002_UNSUPPORTED_DUPLICATE',[{account:'Materials & Supplies',debitCents:48736},{account:'Gulf Coast Business Visa',creditCents:48736}]);track('SUN-L1-01',[sherwin.id],[sherwin.id,`${state.attempt.id}-unsupported-sherwin`],'add unsupported duplicate');
  const owner=entryByDescription(state,'Owner contribution');state=replaceLines(state,owner.id,[{account:'Operating Checking',debitCents:500000},{account:'Painting Income',creditCents:500000}]);track('SUN-L1-03',[owner.id],[owner.id],'credit income instead of equity');
  const loan=entryByDescription(state,'Vehicle loan payment');state=replaceLines(state,loan.id,[{account:'Vehicle Expense',debitCents:92500},{account:'Operating Checking',creditCents:92500}]);track('SUN-L1-04',[loan.id],[loan.id],'expense entire loan payment');
  const washer=entryByDescription(state,'Commercial pressure washer');state=replaceLines(state,washer.id,[{account:'Repairs & Maintenance',debitCents:680000},{account:'Operating Checking',creditCents:680000}]);track('SUN-L1-05',[washer.id],[washer.id],'expense capital asset');
  const trailer=entryByDescription(state,'Enclosed trailer deposit');state=replaceLines(state,trailer.id,[{account:'Uncategorized / Ask My Accountant',debitCents:240000},{account:'Operating Checking',creditCents:240000}]);track('SUN-L1-06',[trailer.id],[trailer.id],'hold in suspense pending support');
  const martinezPayment=state.payments.find(payment=>payment.reference==='RCPT-MARTINEZ-0612')!;const martinezDeposit=state.deposits.find(deposit=>deposit.paymentIds.includes(martinezPayment.id))!;state={...state,deposits:state.deposits.filter(deposit=>deposit.id!==martinezDeposit.id),attempt:{...state.attempt,entries:state.attempt.entries.filter(entry=>entry.id!==martinezDeposit.journalEntryId)}};state=addEntry(state,`${state.attempt.id}-martinez-bank-income`,'2026-06-12','Martinez bank receipt added as income','P002_ADDED_BANK_INCOME',[{account:'Operating Checking',debitCents:385000},{account:'Painting Income',creditCents:385000}]);track('SUN-L1-07',[martinezDeposit.journalEntryId],[`${state.attempt.id}-martinez-bank-income`],'remove deposit link and add bank receipt as income');
  const reynoldsPayment=state.payments.find(payment=>payment.reference==='RCPT-REYNOLDS-0615')!,invoiceA=state.invoices.find(invoice=>invoice.number==='REY-A')!,invoiceB=state.invoices.find(invoice=>invoice.number==='REY-B')!,application=state.applications.find(value=>value.paymentId===reynoldsPayment.id)!;const moved:PaymentApplication={...application,invoiceId:invoiceB.id};state={...state,applications:state.applications.map(value=>value.id===application.id?moved:value),invoices:state.invoices.map(invoice=>invoice.id===invoiceA.id?{...invoice,status:'OPEN'}:invoice.id===invoiceB.id?{...invoice,status:'OPEN'}:invoice)};track('SUN-L1-08',[application.id],[application.id],'apply payment to Invoice B');
  const rent=state.attempt.entries.find(entry=>entry.occurredOn==='2026-06-02'&&entry.description.includes('Rent'))!;state=addEntry(state,`${state.attempt.id}-added-rent`,'2026-06-02','June bank activity added instead of matched','P002_ADDED_NOT_MATCHED',[{account:'Rent',debitCents:250000},{account:'Operating Checking',creditCents:250000}]);track('SUN-L1-11',[rent.id],[rent.id,`${state.attempt.id}-added-rent`],'add bank activity instead of match');
  const capePayment=state.payments.find(payment=>payment.reference==='RCPT-PAINT-0628')!,capeDeposit=state.deposits.find(deposit=>deposit.paymentIds.includes(capePayment.id))!,capeEntry=state.attempt.entries.find(entry=>entry.id===capeDeposit.journalEntryId)!;state=replaceLines(state,capeEntry.id,[{account:'Advertising & Marketing',debitCents:555000},{account:'Undeposited Funds',creditCents:555000}]);track('SUN-L1-12',[capeEntry.id],[capeEntry.id],'record deposit movement as expense');
  const office=state.attempt.entries.find(entry=>entry.occurredOn==='2026-06-18'&&entry.description.includes('Office Depot'))!;state=replaceLines(state,office.id,[{account:'Office Expense',debitCents:38100},{account:'Operating Checking',creditCents:38100}]);track('SUN-L1-13',[office.id],[office.id],'alter reconciled amount from 318 to 381');
  const cardPayment=state.attempt.entries.find(entry=>entry.source?.kind==='CARD_PAYMENT')!;state=replaceLines(state,cardPayment.id,[{account:'Bank Fees',debitCents:350000},{account:'Operating Checking',creditCents:350000}]);track('SUN-L1-15',[cardPayment.id],[cardPayment.id],'expense balance-sheet card payment');
  const payroll=state.attempt.entries.filter(entry=>entry.source?.kind.startsWith('PAYROLL_'));state={...state,attempt:{...state.attempt,entries:state.attempt.entries.filter(entry=>!entry.source?.kind.startsWith('PAYROLL_'))}};const simplifiedPayrollAmounts=[800030,269970,10000] as const;for(const [index,value] of simplifiedPayrollAmounts.entries())state=addEntry(state,`${state.attempt.id}-simplified-payroll-${index+1}`,'2026-06-14','Gulf Coast Payroll withdrawal','P002_SIMPLIFIED_PAYROLL',[{account:'Payroll Expense',debitCents:value},{account:'Operating Checking',creditCents:value}]);track('SUN-L1-16',payroll.map(entry=>entry.id),simplifiedPayrollAmounts.map((_,index)=>`${state.attempt.id}-simplified-payroll-${index+1}`),'retain three provider withdrawals but classify each entirely to payroll expense');
  const homeDepot=state.attempt.entries.filter(entry=>entry.source?.kind==='CARD_PURCHASE'&&entry.occurredOn==='2026-06-22');track('SUN-L1-02',homeDepot.map(entry=>entry.id),homeDepot.map(entry=>entry.id),'retain two supported equal-dollar purchases');
  const jenkins=state.invoices.find(invoice=>invoice.number==='JEN-OPEN')!;track('SUN-L1-09',[jenkins.id],[jenkins.id],'retain supported open receivable');
  const cpa=state.attempt.entries.find(entry=>entry.description.includes('year-end accrual'))!;track('SUN-L1-10',[cpa.id],[cpa.id],'retain supported historical CPA entry');
  const personal=state.attempt.entries.find(entry=>entry.id.endsWith('card-review-0624'))!;track('SUN-L1-14',[personal.id],[personal.id],'hold personal-purpose transaction pending clarification');
  const redundant=state.attempt.accounts.filter(account=>['Advertising','Advertising Expense','Marketing','Marketing & Advertising'].includes(account.name));track('SUN-L1-17',[],redundant.map(account=>account.id),'attempt-only redundant accounts');
  const unapplied=state.payments.find(payment=>payment.reference==='CLIENT-ADVANCE-0630')!;track('SUN-L1-18',[unapplied.id],[unapplied.id],'retain legitimate unapplied customer payment');
  const palm=state.payments.find(payment=>payment.reference==='RCPT-PALM-0626')!;track('SUN-L1-19',[palm.id],[palm.id],'retain supported Palm Breeze receipt');
  return{state,provenance};
}

function addCurrentReconciliations(state:OperationalAttempt,checkingEndingBalanceCents:number,visaEndingBalanceCents:number):OperationalAttempt{const create=(name:string,ending:number):Reconciliation=>{const id=accountId(state,name),lines=state.attempt.entries.filter(entry=>entry.occurredOn>='2026-06-01'&&entry.occurredOn<='2026-06-30').flatMap(entry=>entry.lines).filter(line=>line.attemptAccountId===id);return{id:`${state.attempt.id}-current-${name==='Operating Checking'?'checking':'visa'}`,attemptId:state.attempt.id,accountId:id,beginningDate:'2026-06-01',endingDate:'2026-06-30',beginningBalanceCents:name==='Operating Checking'?suncoastAuthoritativeStatements.checking.beginningBalanceCents:suncoastAuthoritativeStatements.visa.beginningBalanceCents,endingBalanceCents:ending,clearedJournalLineIds:lines.map(line=>line.id),clearedLineFingerprints:Object.fromEntries(lines.map(line=>[line.id,`${line.debitCents}:${line.creditCents}:${line.attemptAccountId}`])),status:'IN_PROGRESS'};};return{...state,reconciliations:[...state.reconciliations,create('Operating Checking',checkingEndingBalanceCents),create('Gulf Coast Business Visa',visaEndingBalanceCents)]}}

export async function deriveP002StudentStart(studentId:string,attemptId:string,generation=1):Promise<P002InstructorState>{const cleanMaster=await buildSuncoastMasterCase();let state=cloneMaster(cleanMaster,studentId,attemptId,generation);state=addAttemptAccounts(state);state=addNewLegitimateActivity(state);const transformed=applyStartingErrors(state);const authoritativeStatements={checkingEndingBalanceCents:suncoastAuthoritativeStatements.checking.endingBalanceCents+75000,visaEndingBalanceCents:suncoastAuthoritativeStatements.visa.endingBalanceCents+28643};state=addCurrentReconciliations(transformed.state,authoritativeStatements.checkingEndingBalanceCents,authoritativeStatements.visaEndingBalanceCents);const reconciliationProvenance:ScenarioProvenance={scenarioId:'SUN-L1-20',cleanRecordIds:[],studentRecordIds:state.reconciliations.filter(item=>item.id.includes('-current-')).map(item=>item.id),transformation:'current reconciliation consequence'};const visibleDocuments=cleanMaster.studentMetadata.filter(document=>!document.id.startsWith('JUN-PAYROLL')&&document.id!=='ABC-TRAILER-0617').map(document=>({...document,available:true}));return{attempt:{state,visibleDocuments,auditTrail:[]},scenarios:p002ScenarioDefinitions,provenance:[...transformed.provenance,reconciliationProvenance],hiddenFacts,criticalHooks,authoritativeStatements,cleanMaster};}
export async function buildResolvedP002State(studentId:string,attemptId:string,generation=1):Promise<OperationalAttempt>{const master=await buildSuncoastMasterCase();let state=cloneMaster(master,studentId,attemptId,generation);state=addAttemptAccounts(state);state=addNewLegitimateActivity(state,true);return addCurrentReconciliations(state,suncoastAuthoritativeStatements.checking.endingBalanceCents+75000,suncoastAuthoritativeStatements.visa.endingBalanceCents+28643);}

export function p002StudentView(value:P002InstructorState){const neutralEntries=value.attempt.state.attempt.entries.map(entry=>{if(!entry.source?.kind.startsWith('P002_'))return entry;const card=entry.id.endsWith('card-review-0624')||entry.id.endsWith('unsupported-sherwin');return{...entry,description:card?'Credit-card purchase':'Bookkeeping activity',source:{kind:card?'CARD_PURCHASE':'BANK_ACTIVITY',id:entry.id}}});const neutralState={...value.attempt.state,attempt:{...value.attempt.state.attempt,entries:neutralEntries}};return{attempt:studentView(neutralState.attempt),operations:operationalStudentView(neutralState),documents:value.attempt.visibleDocuments,auditTrail:value.attempt.auditTrail.map(event=>({sequence:event.sequence,at:event.at,action:event.action,targetId:event.targetId,selfCorrected:event.selfCorrected,revision:event.revision}))}}
export function recordP002Action(value:P002InstructorState,action:P002ActionKind,targetId:string,options:{hook?:P002CriticalHook;verifiedCorrect?:boolean;selfCorrected?:boolean;helpLevel?:'HINT'|'DIRECTION'|'WALKTHROUGH';commandId?:string;revision?:number;note?:string;visibleDocumentIds?:readonly string[];before?:unknown;after?:unknown}={}):P002InstructorState{const event:P002AuditEvent={sequence:value.attempt.auditTrail.length+1,at:`2026-07-02T10:${String(value.attempt.auditTrail.length).padStart(2,'0')}:00.000Z`,action,targetId,...options};return{...value,attempt:{...value.attempt,auditTrail:[...value.attempt.auditTrail,event]}}}
export async function resetP002Attempt(value:P002InstructorState,newAttemptId:string):Promise<{old:P002InstructorState;next:P002InstructorState}>{const old={...value,attempt:{...value.attempt,state:{...value.attempt.state,attempt:{...value.attempt.state.attempt,status:'RESET' as const}}}};const next=await deriveP002StudentStart(value.attempt.state.attempt.studentId,newAttemptId,value.attempt.state.attempt.generation+1);return{old,next}}
export function p002FinancialSnapshot(value:P002InstructorState){const state=value.attempt.state;const checking=state.reconciliations.find(item=>item.id.endsWith('current-checking'))!,visa=state.reconciliations.find(item=>item.id.endsWith('current-visa'))!,historical=state.reconciliations.filter(item=>item.status==='COMPLETED').map(item=>reconciliationResult(state,item));return{cashJune:operationalProfitAndLoss(state,'CASH',{from:'2026-06-01',through:'2026-06-30'}),accrualJune:operationalProfitAndLoss(state,'ACCRUAL',{from:'2026-06-01',through:'2026-06-30'}),balanceSheet:balanceSheet(state.attempt),trialBalance:trialBalance(state.attempt),ar:{details:invoiceDetails(state),customers:customerBalances(state),controlDifferenceCents:arControlDifference(state,accountId(state,'Accounts Receivable'))},undepositedFundsCents:trialBalance(state.attempt).find(row=>row.name==='Undeposited Funds')!.debitCents,checking:reconciliationResult(state,checking),visa:reconciliationResult(state,visa),historical};}
