import { InvalidReferenceError, InvalidStateError, NotFoundError } from './errors.js';
import { competencyWeights, totalRubricPoints, type AssessmentEvidence, type AssessmentSnapshot, type Competency, type CompetencyResult, type ReadinessClassification, type SuncoastAssessmentAttempt } from './suncoast-assessment.js';
import type { SuncoastMonthEndMeeting } from './suncoast-month-end.js';

export type CompetencyLabel = 'STRONG' | 'PROFICIENT' | 'DEVELOPING' | 'NEEDS_PRACTICE' | 'NOT_ASSESSED';
export interface ReportNarrative { readonly text: string; readonly sourceRefs: readonly string[] }
export interface StudentCompetencyReport { readonly competency: Competency; readonly displayName: string; readonly earnedPoints: number | null; readonly availablePoints: number; readonly label: CompetencyLabel; readonly interpretation: ReportNarrative; readonly strengths: readonly ReportNarrative[]; readonly development: readonly ReportNarrative[] }
export interface ReadinessReportSnapshot {
  readonly id: string; readonly attemptId: string; readonly studentId: string; readonly attemptNumber: number; readonly version: number; readonly assessmentSnapshotId: string; readonly rubricVersion: string; readonly generatedAt: string; readonly completionAt: string;
  readonly canonicalClassification: ReadinessClassification; readonly displayClassification: string; readonly pointsEarned: number; readonly pointsAssessed: number; readonly totalRubricPoints: number; readonly caseName: 'Suncoast Home Services LLC';
  readonly overallSummary: ReportNarrative; readonly competencies: readonly StudentCompetencyReport[]; readonly strengths: readonly ReportNarrative[]; readonly development: readonly ReportNarrative[]; readonly independenceSummary: ReportNarrative; readonly selfCorrectionSummary?: ReportNarrative; readonly criticalSummary?: ReportNarrative; readonly communicationSummary: ReportNarrative; readonly monthEndSummary: ReportNarrative; readonly nextStep: ReportNarrative; readonly targetedPractice: readonly ReportNarrative[];
}
export interface ReadinessReportHistory { readonly attemptId: string; readonly studentId: string; readonly attemptNumber: number; readonly reports: readonly ReadinessReportSnapshot[] }

const freeze = <T>(value: T): T => { if (value && typeof value === 'object' && !Object.isFrozen(value)) { Object.freeze(value); for (const child of Object.values(value)) freeze(child); } return value; };
const generatedAt = (version: number) => `2026-07-08T15:${String(version).padStart(2, '0')}:00.000Z`;
const displayNames: Readonly<Record<Competency, string>> = Object.freeze({ TECHNICAL_BOOKKEEPING: 'Technical Bookkeeping', INVESTIGATION_PROBLEM_SOLVING: 'Investigation & Problem Solving', PROFESSIONAL_JUDGMENT: 'Professional Judgment', CLIENT_COMMUNICATION: 'Client Communication', MONTH_END_FINANCIAL_EXPLANATION: 'Month-End Financial Explanation' });
const displayClassifications: Readonly<Record<ReadinessClassification, string>> = Object.freeze({ CLIENT_READY: 'Client Ready', CLIENT_READY_WITH_SUPPORT: 'Client Ready With Support', MORE_PRACTICE_NEEDED: 'More Practice Recommended', RETURN_TO_LAB: 'Return to the Practice Lab', INCOMPLETE: 'Assessment Incomplete', REQUIRES_REVIEW: 'BBB Review Required' });

export function canonicalReadinessReportDefinition() { return Object.freeze({displayNames,displayClassifications,brand:'BBB Client Practice Lab',title:'Are You Really Ready for Clients?',caseName:'Suncoast Home Services LLC',totalRubricPoints}); }

export function competencyLabel(result: CompetencyResult): CompetencyLabel {
  if (result.status === 'NOT_ASSESSED' || result.earnedPoints === null) return 'NOT_ASSESSED';
  const percent = result.availablePoints === 0 ? 0 : result.earnedPoints * 100 / result.availablePoints;
  return percent >= 90 ? 'STRONG' : percent >= 80 ? 'PROFICIENT' : percent >= 70 ? 'DEVELOPING' : 'NEEDS_PRACTICE';
}
function narrative(text: string, sourceRefs: readonly string[]): ReportNarrative { if (sourceRefs.length === 0) throw new InvalidStateError('Report narrative lacks evidence'); return freeze({ text, sourceRefs: [...new Set(sourceRefs)] }); }
function evidenceThrough(assessment: SuncoastAssessmentAttempt, snapshot: AssessmentSnapshot): readonly AssessmentEvidence[] { return assessment.evidence.filter(item => item.sequence <= snapshot.evidenceThroughSequence); }
function validateAssessment(assessment: SuncoastAssessmentAttempt, snapshot: AssessmentSnapshot) {
  if (snapshot.attemptId !== assessment.attemptId || snapshot.rubricVersion !== assessment.rubricVersion) throw new InvalidReferenceError('Report unavailable');
  if (snapshot.competencies.length !== 5 || new Set(snapshot.competencies.map(item => item.competency)).size !== 5) throw new InvalidStateError('Report unavailable');
  if (!displayClassifications[snapshot.classification] || snapshot.competencies.some(item => competencyWeights[item.competency] !== item.availablePoints || item.earnedPoints !== null && (item.earnedPoints < 0 || item.earnedPoints > item.availablePoints) || item.status === 'NOT_ASSESSED' !== (item.earnedPoints === null))) throw new InvalidStateError('Report unavailable');
  const earned = snapshot.competencies.reduce((sum, item) => sum + (item.earnedPoints ?? 0), 0); const assessed = snapshot.competencies.filter(item => item.status === 'ASSESSED').reduce((sum, item) => sum + item.availablePoints, 0);
  if (earned !== snapshot.pointsEarned || assessed !== snapshot.pointsAssessed || snapshot.competencies.reduce((sum, item) => sum + item.availablePoints, 0) !== totalRubricPoints) throw new InvalidStateError('Report unavailable');
  const eligibleEvidence = new Set(evidenceThrough(assessment, snapshot).map(item => item.id));
  if (evidenceThrough(assessment, snapshot).some(item => item.attemptId !== assessment.attemptId || item.source.attemptId !== assessment.attemptId)) throw new InvalidReferenceError('Report unavailable');
  const references = [...snapshot.competencies.flatMap(item => item.evidenceIds), ...snapshot.criticalEvents.flatMap(item => item.sourceEvidenceIds)];
  if (references.some(id => !eligibleEvidence.has(id))) throw new InvalidReferenceError('Report unavailable');
}
function interpretation(result: CompetencyResult, label: CompetencyLabel, snapshotId: string): ReportNarrative {
  const name = displayNames[result.competency]; const refs = result.evidenceIds.length ? result.evidenceIds : [snapshotId];
  const text = label === 'STRONG' ? `Your ${name} evidence was consistently strong.` : label === 'PROFICIENT' ? `Your ${name} evidence showed reliable performance with limited support needs.` : label === 'DEVELOPING' ? `Your ${name} evidence showed a useful foundation with areas still developing.` : label === 'NEEDS_PRACTICE' ? `Your ${name} evidence shows that more focused practice is needed.` : `${name} has not yet been assessed.`;
  return narrative(text, refs);
}
function competencyReport(result: CompetencyResult, snapshotId: string): StudentCompetencyReport {
  const label = competencyLabel(result), meaning = interpretation(result, label, snapshotId), name = displayNames[result.competency];
  const strengths = ['STRONG', 'PROFICIENT'].includes(label) ? [narrative(`${name} was a demonstrated strength in this attempt.`, meaning.sourceRefs)] : [];
  const development = ['DEVELOPING', 'NEEDS_PRACTICE'].includes(label) || result.helpDependent ? [narrative(result.helpDependent ? `Continue practicing ${name} with the goal of completing similar work more independently.` : `Continue targeted practice in ${name}.`, meaning.sourceRefs)] : [];
  return freeze({ competency: result.competency, displayName: name, earnedPoints: result.earnedPoints, availablePoints: result.availablePoints, label, interpretation: meaning, strengths, development });
}
function criticalSummary(snapshot: AssessmentSnapshot): ReportNarrative | undefined {
  const unresolved = snapshot.criticalEvents.filter(item => item.state === 'TRIGGERED_UNRESOLVED'); if (unresolved.length) return narrative("One or more decisions created a material risk to the accuracy of the client's books and still require review.", unresolved.flatMap(item => item.sourceEvidenceIds));
  const coached = snapshot.criticalEvents.filter(item => item.state === 'TRIGGERED_AFTER_COACHING_CORRECTED'); if (coached.length) return narrative('You made a high-risk bookkeeping decision and corrected it after coaching. The correction matters, and this area still needs independent practice before live-client responsibility.', coached.flatMap(item => item.sourceEvidenceIds));
  const selfCorrected = snapshot.criticalEvents.filter(item => item.state === 'TRIGGERED_SELF_CORRECTED'); if (selfCorrected.length) return narrative('You made a high-risk bookkeeping decision and later corrected it through your own review. The recovery matters, and the original risk remains part of this attempt.', selfCorrected.flatMap(item => item.sourceEvidenceIds));
  return undefined;
}
function independenceSummary(evidence: readonly AssessmentEvidence[], snapshot: AssessmentSnapshot): ReportNarrative {
  const assessable = evidence.filter(item => item.outcome !== 'OBSERVED'); const refs = assessable.map(item => item.id); if (refs.length === 0) return narrative('No assessed independence evidence is available yet.', [snapshot.id]);
  const helped = assessable.filter(item => item.helpState !== 'INDEPENDENT'); const helpDependent = snapshot.competencies.some(item => item.helpDependent); const walkthrough = helped.some(item => item.helpState === 'WALKTHROUGH_USED'); const direction = helped.some(item => item.helpState === 'DIRECTION_USED');
  const text = helped.length === 0 ? 'The assessed work was completed independently.' : helpDependent && walkthrough ? 'The authoritative assessment identifies meaningful walkthrough dependence. Continue practicing these competencies before handling similar work alone.' : helpDependent ? 'The authoritative assessment identifies meaningful support dependence in at least one competency. Continue building independence in the identified areas.' : direction ? 'The authoritative assessment did not identify overall help dependence, though directional support was used in some assessed work.' : 'The authoritative assessment did not identify overall help dependence, though occasional hints were used.';
  return narrative(text, refs);
}
function selfCorrectionSummary(evidence: readonly AssessmentEvidence[]): ReportNarrative | undefined {
  const corrections = evidence.filter(item => item.selfCorrected); if (!corrections.length) return undefined; const independent = corrections.filter(item => item.helpState === 'INDEPENDENT').length; const substantial = corrections.some(item => item.helpState === 'WALKTHROUGH_USED');
  const text = substantial ? 'You corrected earlier work, including an area that required substantial assistance. The recovery is meaningful, and continued independent practice is recommended.' : independent > 0 ? 'You identified and corrected earlier work through your own review. That is useful evidence of problem-solving and recovery.' : 'You corrected earlier work after using support. The correction is meaningful while the help history remains part of the result.';
  return narrative(text, corrections.map(item => item.id));
}
function communicationSummary(result: CompetencyResult, snapshotId: string): ReportNarrative { const label = competencyLabel(result); const refs = result.evidenceIds.length ? result.evidenceIds : [snapshotId]; const text = label === 'NOT_ASSESSED' ? 'Client communication has not yet been assessed.' : label === 'STRONG' ? 'The authoritative assessment rated your demonstrated client communication Strong.' : label === 'PROFICIENT' ? 'The authoritative assessment rated your demonstrated client communication Proficient.' : label === 'DEVELOPING' ? 'The authoritative assessment rated your demonstrated client communication Developing; continue practicing this competency.' : 'The authoritative assessment rated your demonstrated client communication Needs Practice; complete targeted communication practice before relying on this skill with a live client.'; return narrative(text, refs); }
function monthEndSummary(result: CompetencyResult, snapshotId: string, meeting?: SuncoastMonthEndMeeting): ReportNarrative {
  const refs = result.evidenceIds.length ? result.evidenceIds : [snapshotId]; if (result.status === 'NOT_ASSESSED') return narrative('The month-end financial explanation has not yet been completed.', refs);
  const evidence = meeting?.explanationEvidence; if (!evidence) return narrative(`The authoritative assessment rated your Month-End Financial Explanation ${competencyLabel(result).replaceAll('_', ' ')}.`, refs);
  const names = { FINANCIAL_ACCURACY: 'financial accuracy', RELEVANCE: 'relevance', CLARITY: 'clarity', BUSINESS_INSIGHT: 'business insight', PROFESSIONAL_COMMUNICATION: 'professional communication' } as const;
  const dimensions = evidence.dimensions.map(item => `${names[item.dimension]} ${item.earnedPoints === item.availablePoints ? 'met' : item.earnedPoints === 0 ? 'needs practice' : 'is developing'}`);
  return narrative(`P-007 assessed your month-end explanation as follows: ${dimensions.join('; ')}.`, refs);
}
function nextStep(classification: ReadinessClassification, snapshotId: string): ReportNarrative { const text: Record<ReadinessClassification, string> = { CLIENT_READY: 'Based on the Lab 1 evidence, BBB recommends progressing toward client work. Continue using appropriate support for unfamiliar situations; this result is not a certification, license, or guarantee of client outcomes.', CLIENT_READY_WITH_SUPPORT: 'Based on the Lab 1 evidence, BBB recommends progressing toward client work with support available. Continue practicing the identified areas before working independently.', MORE_PRACTICE_NEEDED: 'Complete targeted practice in the identified areas, then return to the Client Practice Lab for another attempt.', RETURN_TO_LAB: 'Return to the practice environment and work through the recommended areas before taking on live client responsibility.', INCOMPLETE: 'Complete the remaining required portion of the lab before a readiness recommendation can be issued.', REQUIRES_REVIEW: 'A final readiness recommendation has not been issued. This attempt is marked for BBB review.', }; return narrative(text[classification], [snapshotId]); }

export function generateReadinessReport(history: ReadinessReportHistory | null, assessment: SuncoastAssessmentAttempt, meeting?: SuncoastMonthEndMeeting): ReadinessReportHistory {
  const snapshot = assessment.snapshots.at(-1); if (!snapshot) throw new InvalidStateError('Report unavailable'); validateAssessment(assessment, snapshot);
  if (history && (history.attemptId !== assessment.attemptId || history.studentId !== assessment.studentId)) throw new InvalidReferenceError('Report unavailable');
  if (meeting && (meeting.attemptId !== assessment.attemptId || meeting.studentId !== assessment.studentId)) throw new InvalidReferenceError('Report unavailable');
  const monthEndEvidence = snapshot.competencies.find(item => item.competency === 'MONTH_END_FINANCIAL_EXPLANATION')?.evidenceIds ?? [];
  if (meeting?.explanationEvidence && !assessment.evidence.some(item => monthEndEvidence.includes(item.id) && item.source.id === meeting.explanationEvidence?.id)) throw new InvalidReferenceError('Report unavailable');
  if (history?.reports.at(-1)?.assessmentSnapshotId === snapshot.id) return history;
  const evidence = evidenceThrough(assessment, snapshot), competencies = snapshot.competencies.map(item => competencyReport(item, snapshot.id)), strengths = competencies.flatMap(item => item.strengths), development = competencies.flatMap(item => item.development);
  const strongNames = competencies.filter(item => ['STRONG', 'PROFICIENT'].includes(item.label)).map(item => item.displayName); const developingNames = competencies.filter(item => ['DEVELOPING', 'NEEDS_PRACTICE'].includes(item.label)).map(item => item.displayName);
  const summaryText = strongNames.length ? `Your evidence showed strength in ${strongNames.join(' and ')}.${developingNames.length ? ` Continue developing ${developingNames.join(' and ')}.` : ''} Your readiness result is ${displayClassifications[snapshot.classification]}.` : `Your readiness result is ${displayClassifications[snapshot.classification]}.${developingNames.length ? ` Continue targeted work in ${developingNames.join(' and ')}.` : ''}`;
  const critical = criticalSummary(snapshot), selfCorrection = selfCorrectionSummary(evidence), communication = snapshot.competencies.find(item => item.competency === 'CLIENT_COMMUNICATION')!, monthEnd = snapshot.competencies.find(item => item.competency === 'MONTH_END_FINANCIAL_EXPLANATION')!;
  const targetedPractice = competencies.filter(item => item.development.length).map(item => narrative(`${item.displayName}: ${item.development[0].text}`, item.development[0].sourceRefs));
  const version = (history?.reports.length ?? 0) + 1; const report: ReadinessReportSnapshot = freeze({ id: `${assessment.attemptId}-readiness-report-${version}`, attemptId: assessment.attemptId, studentId: assessment.studentId, attemptNumber: assessment.generation, version, assessmentSnapshotId: snapshot.id, rubricVersion: snapshot.rubricVersion, generatedAt: generatedAt(version), completionAt: snapshot.evaluatedAt, canonicalClassification: snapshot.classification, displayClassification: displayClassifications[snapshot.classification], pointsEarned: snapshot.pointsEarned, pointsAssessed: snapshot.pointsAssessed, totalRubricPoints, caseName: 'Suncoast Home Services LLC', overallSummary: narrative(summaryText, [snapshot.id, ...competencies.flatMap(item => item.interpretation.sourceRefs)]), competencies, strengths, development, independenceSummary: independenceSummary(evidence, snapshot), selfCorrectionSummary: selfCorrection, criticalSummary: critical, communicationSummary: communicationSummary(communication, snapshot.id), monthEndSummary: monthEndSummary(monthEnd, snapshot.id, meeting), nextStep: nextStep(snapshot.classification, snapshot.id), targetedPractice });
  return freeze({ attemptId: assessment.attemptId, studentId: assessment.studentId, attemptNumber: assessment.generation, reports: [...(history?.reports ?? []), report] });
}

const publicNarrative = (value: ReportNarrative) => value.text;
export function readinessReportStudentView(history: ReadinessReportHistory) { const report = history.reports.at(-1); if (!report) throw new NotFoundError('Report not found'); return freeze({ header: { brand: 'BBB Client Practice Lab', title: 'Are You Really Ready for Clients?', result: report.displayClassification, canonicalClassification: report.canonicalClassification, caseName: report.caseName, rubricVersion: report.rubricVersion, completionAt: report.completionAt }, attemptNumber: report.attemptNumber, reportVersion: report.version, generatedAt: report.generatedAt, points: { earned: report.pointsEarned, assessed: report.pointsAssessed, total: report.totalRubricPoints }, overallSummary: publicNarrative(report.overallSummary), competencies: report.competencies.map(item => ({ competency: item.competency, displayName: item.displayName, earnedPoints: item.earnedPoints, availablePoints: item.availablePoints, label: item.label, interpretation: publicNarrative(item.interpretation), strengths: item.strengths.map(publicNarrative), development: item.development.map(publicNarrative) })), whatYouDidWell: report.strengths.map(publicNarrative), whatToKeepPracticing: report.development.map(publicNarrative), independenceSummary: publicNarrative(report.independenceSummary), selfCorrectionSummary: report.selfCorrectionSummary ? publicNarrative(report.selfCorrectionSummary) : undefined, criticalSummary: report.criticalSummary ? publicNarrative(report.criticalSummary) : undefined, communicationSummary: publicNarrative(report.communicationSummary), monthEndSummary: publicNarrative(report.monthEndSummary), recommendedNextStep: publicNarrative(report.nextStep), targetedPractice: report.targetedPractice.map(publicNarrative), history: history.reports.map(item => ({ attemptNumber: item.attemptNumber, reportVersion: item.version, completionAt: item.completionAt, classification: item.canonicalClassification, displayClassification: item.displayClassification, pointsEarned: item.pointsEarned, totalRubricPoints: item.totalRubricPoints })) }); }
export function authorizedReadinessReportView(history: ReadinessReportHistory) { return history; }

export interface ReadinessReportStore { findForStudent(attemptId: string, studentId: string): Promise<ReadinessReportHistory | null>; save(value: ReadinessReportHistory): Promise<void> }
export class ReadinessReportService { constructor(private readonly store: ReadinessReportStore) {} async view(studentId: string, attemptId: string) { const value = await this.store.findForStudent(attemptId, studentId); if (!value) throw new NotFoundError('Report not found'); return readinessReportStudentView(value); } }
