import { InvalidReferenceError } from './errors.js';
import type { OperationalAttempt } from './operations-model.js';
import { deriveP002StudentStart, type P002InstructorState } from './suncoast-student-start.js';
import { suncoastPayrollTruth } from './suncoast-master.js';

export type EvidenceState='AVAILABLE_AT_START'|'LOCKED_REQUESTABLE'|'UNLOCKED'|'UNAVAILABLE'|'INSTRUCTOR_ONLY';
export type EvidenceAuditKind='DOCUMENT_LIST_VIEWED'|'DOCUMENT_OPENED'|'DOCUMENT_DOWNLOADED'|'DOCUMENT_REQUESTED'|'DOCUMENT_UNLOCKED'|'REFERENCE_FOLLOWED';
export interface EvidenceFact {readonly label:string;readonly value:string|number}
export interface EvidenceLink {readonly recordType:'JOURNAL_ENTRY'|'INVOICE'|'PAYMENT'|'DEPOSIT'|'RECONCILIATION'|'STATEMENT_TRUTH';readonly recordId:string;readonly relationship:string}
export interface EvidenceDocument {readonly id:string;readonly type:string;readonly title:string;readonly date:string;readonly issuer:string;readonly state:EvidenceState;readonly facts:readonly EvidenceFact[];readonly links:readonly EvidenceLink[]}
export interface EvidenceAuditEvent {readonly sequence:number;readonly at:string;readonly kind:EvidenceAuditKind;readonly documentId?:string;readonly referenceId?:string}
interface UnlockRule {readonly documentId:string;readonly authorization:'DOCUMENT_REQUESTED'|'CLIENT_CLARIFICATION_COMPLETED'|'SYSTEM_ACTION';readonly requestSubject:string}
interface InstructorEvidenceDocument extends EvidenceDocument {readonly interpretation:string}
export interface SuncoastEvidenceAttempt {readonly attemptId:string;readonly studentId:string;readonly generation:number;readonly documents:readonly InstructorEvidenceDocument[];readonly audit:readonly EvidenceAuditEvent[];readonly unlockRules:readonly UnlockRule[];readonly p002:P002InstructorState}

const checkingStatements=Object.freeze([
  {period:'April 2026',from:'2026-04-01',through:'2026-04-30',beginningBalanceCents:2845000,endingBalanceCents:4441000},
  {period:'May 2026',from:'2026-05-01',through:'2026-05-31',beginningBalanceCents:4441000,endingBalanceCents:6992500},
  {period:'June 2026',from:'2026-06-01',through:'2026-06-30',beginningBalanceCents:6992500,endingBalanceCents:8442200},
]);
const visaStatements=Object.freeze([
  {period:'April 2026',from:'2026-04-01',through:'2026-04-30',beginningBalanceCents:485000,endingBalanceCents:545000},
  {period:'May 2026',from:'2026-05-01',through:'2026-05-31',beginningBalanceCents:545000,endingBalanceCents:575000},
  {period:'June 2026',from:'2026-06-01',through:'2026-06-30',beginningBalanceCents:575000,endingBalanceCents:430815},
]);

const fact=(label:string,value:string|number):EvidenceFact=>({label,value});
const freezeDocument=(document:InstructorEvidenceDocument):InstructorEvidenceDocument=>Object.freeze({...document,facts:Object.freeze([...document.facts]),links:Object.freeze([...document.links])});
const findEntry=(state:OperationalAttempt,predicate:(description:string,kind:string|undefined,date:string)=>boolean)=>{const entry=state.attempt.entries.find(item=>predicate(item.description,item.source?.kind,item.occurredOn));if(!entry)throw new Error('Authoritative evidence link unavailable');return entry.id};
const invoice=(state:OperationalAttempt,number:string)=>{const value=state.invoices.find(item=>item.number===number);if(!value)throw new Error(`Invoice ${number} unavailable`);return value};
const payment=(state:OperationalAttempt,reference:string)=>{const value=state.payments.find(item=>item.reference===reference);if(!value)throw new Error(`Payment ${reference} unavailable`);return value};
const depositFor=(state:OperationalAttempt,paymentId:string)=>{const value=state.deposits.find(item=>item.paymentIds.includes(paymentId));if(!value)throw new Error('Deposit unavailable');return value};

function canonicalDocuments(p002:P002InstructorState):readonly InstructorEvidenceDocument[]{const state=p002.attempt.state;const available='AVAILABLE_AT_START' as const,locked='LOCKED_REQUESTABLE' as const;
  const documents:InstructorEvidenceDocument[]=[
    {id:'client-profile',type:'CLIENT_INFORMATION',title:'Suncoast Home Services — Client Information',date:'2026-04-01',issuer:'Suncoast Home Services LLC',state:available,facts:[fact('Company','Suncoast Home Services LLC'),fact('Activities','Residential handyman, painting, and pressure-washing services'),fact('Entity type','Florida limited liability company'),fact('Owner','Michael Carter'),fact('Accounting basis','Accrual books with cash-basis management reporting'),fact('Bank','Gulf Coast Community Bank'),fact('Credit card','Gulf Coast Business Visa'),fact('Payroll provider','Gulf Coast Payroll Services'),fact('CPA','Coastal Accounting & Tax'),fact('Customer process','Invoices are issued for services; checks and ACH receipts may pass through Undeposited Funds before bank deposit')],links:[],interpretation:'General onboarding context only; it identifies no planted issue.'},
    ...checkingStatements.map(statement=>({id:`checking-${statement.from.slice(0,7)}`,type:'BANK_STATEMENT',title:`Operating Checking Statement — ${statement.period}`,date:statement.through,issuer:'Gulf Coast Community Bank',state:available,facts:[fact('Period start',statement.from),fact('Period end',statement.through),fact('Beginning balance',statement.beginningBalanceCents),fact('Ending balance',statement.endingBalanceCents)],links:[{recordType:'STATEMENT_TRUTH' as const,recordId:`checking-${statement.from}`,relationship:'Independent external statement period'}],interpretation:'Independent statement truth; never derived from the student ledger.'})),
    ...visaStatements.map(statement=>({id:`visa-${statement.from.slice(0,7)}`,type:'CARD_STATEMENT',title:`Gulf Coast Business Visa Statement — ${statement.period}`,date:statement.through,issuer:'Gulf Coast Community Bank',state:available,facts:[fact('Period start',statement.from),fact('Period end',statement.through),fact('Beginning balance',statement.beginningBalanceCents),fact('Ending balance',statement.endingBalanceCents),...(statement.period==='June 2026'?[fact('June 24 transaction',28643)]:[])],links:[{recordType:'STATEMENT_TRUTH' as const,recordId:`visa-${statement.from}`,relationship:'Independent external statement period'}],interpretation:statement.period==='June 2026'?'The $286.43 line is personal, but the statement itself does not establish purpose.':'Independent statement truth.'})),
    {id:'vehicle-loan-june',type:'LOAN_STATEMENT',title:'Gulf Coast Auto Finance — June Loan Statement',date:'2026-06-30',issuer:'Gulf Coast Auto Finance',state:available,facts:[fact('June payment',92500),fact('Principal',69000),fact('Interest',23500),fact('Ending principal balance',2791000)],links:[{recordType:'JOURNAL_ENTRY',recordId:findEntry(state,description=>description==='Vehicle loan payment'),relationship:'Supports June loan payment allocation'}],interpretation:'The student starting entry is fully expensed and should be allocated per this statement.'},
    {id:'martinez-invoice',type:'CUSTOMER_INVOICE',title:'Invoice JUN-1010 — Susan Martinez',date:'2026-06-05',issuer:'Suncoast Home Services LLC',state:available,facts:[fact('Invoice number','JUN-1010'),fact('Amount',385000),fact('Service','Painting services')],links:[{recordType:'INVOICE',recordId:invoice(state,'JUN-1010').id,relationship:'Source invoice'}],interpretation:'Legitimate invoice in the Martinez lifecycle.'},
    {id:'martinez-remittance',type:'CUSTOMER_REMITTANCE',title:'Susan Martinez Remittance',date:'2026-06-12',issuer:'Susan Martinez',state:available,facts:[fact('Amount',385000),fact('Reference','RCPT-MARTINEZ-0612')],links:[{recordType:'PAYMENT',recordId:payment(state,'RCPT-MARTINEZ-0612').id,relationship:'Supports customer payment'}],interpretation:'Supports the legitimate payment, not a second revenue event.'},
    {id:'reynolds-invoice-a',type:'CUSTOMER_INVOICE',title:'Invoice REY-A — David Reynolds',date:'2026-06-03',issuer:'Suncoast Home Services LLC',state:available,facts:[fact('Invoice','REY-A'),fact('Amount',185000)],links:[{recordType:'INVOICE',recordId:invoice(state,'REY-A').id,relationship:'Source invoice'}],interpretation:'The Reynolds payment belongs to this invoice.'},
    {id:'reynolds-invoice-b',type:'CUSTOMER_INVOICE',title:'Invoice REY-B — David Reynolds',date:'2026-06-18',issuer:'Suncoast Home Services LLC',state:available,facts:[fact('Invoice','REY-B'),fact('Amount',227500)],links:[{recordType:'INVOICE',recordId:invoice(state,'REY-B').id,relationship:'Source invoice'}],interpretation:'This invoice remains open in clean truth.'},
    {id:'reynolds-remittance',type:'CUSTOMER_REMITTANCE',title:'David Reynolds Remittance',date:'2026-06-15',issuer:'David Reynolds',state:available,facts:[fact('Amount',185000),fact('Invoice reference','REY-A')],links:[{recordType:'PAYMENT',recordId:payment(state,'RCPT-REYNOLDS-0615').id,relationship:'Supports customer payment'}],interpretation:'Visible reference supports application to Invoice A.'},
    {id:'jenkins-invoice',type:'CUSTOMER_INVOICE',title:'Invoice JEN-OPEN — Robert Jenkins',date:'2026-06-22',issuer:'Suncoast Home Services LLC',state:available,facts:[fact('Invoice','JEN-OPEN'),fact('Amount',142500),fact('Status','Unpaid')],links:[{recordType:'INVOICE',recordId:invoice(state,'JEN-OPEN').id,relationship:'Source invoice'}],interpretation:'The invoice exists and remains unpaid; collectibility intent is separately protected.'},
    {id:'palm-invoice',type:'CUSTOMER_INVOICE',title:'Invoice JUN-1011 — Palm Breeze Property Management',date:'2026-06-20',issuer:'Suncoast Home Services LLC',state:available,facts:[fact('Invoice','JUN-1011'),fact('Amount',950000)],links:[{recordType:'INVOICE',recordId:invoice(state,'JUN-1011').id,relationship:'Source invoice'}],interpretation:'Legitimate supported invoice.'},
    {id:'palm-remittance',type:'CUSTOMER_REMITTANCE',title:'Palm Breeze Remittance',date:'2026-06-26',issuer:'Palm Breeze Property Management',state:available,facts:[fact('Amount',950000),fact('Reference','RCPT-PALM-0626')],links:[{recordType:'PAYMENT',recordId:payment(state,'RCPT-PALM-0626').id,relationship:'Supports customer payment'}],interpretation:'Legitimate $9,500 receipt.'},
    {id:'palm-deposit',type:'BANK_DEPOSIT_SUPPORT',title:'June 26 Bank Deposit Detail',date:'2026-06-26',issuer:'Gulf Coast Community Bank',state:available,facts:[fact('Amount',950000)],links:[{recordType:'DEPOSIT',recordId:depositFor(state,payment(state,'RCPT-PALM-0626').id).id,relationship:'Supports bank deposit'}],interpretation:'Completes the legitimate Palm Breeze lifecycle.'},
    {id:'home-depot-jenkins',type:'VENDOR_RECEIPT',title:'Home Depot Receipt — June 22 Morning',date:'2026-06-22',issuer:'Home Depot',state:available,facts:[fact('Amount',64218),fact('Job reference','Jenkins')],links:[{recordType:'JOURNAL_ENTRY',recordId:findEntry(state,(_,kind,date)=>kind==='CARD_PURCHASE'&&date==='2026-06-22'),relationship:'Supports distinct card purchase'}],interpretation:'One of two legitimate equal-dollar purchases.'},
    {id:'home-depot-palm',type:'VENDOR_RECEIPT',title:'Home Depot Receipt — June 22 Afternoon',date:'2026-06-22',issuer:'Home Depot',state:available,facts:[fact('Amount',64218),fact('Job reference','Palm Breeze')],links:[{recordType:'JOURNAL_ENTRY',recordId:state.attempt.entries.filter(entry=>entry.source?.kind==='CARD_PURCHASE'&&entry.occurredOn==='2026-06-22')[1].id,relationship:'Supports distinct card purchase'}],interpretation:'The other legitimate equal-dollar purchase.'},
    {id:'sherwin-receipt',type:'VENDOR_RECEIPT',title:'Sherwin-Williams Receipt — June 25',date:'2026-06-25',issuer:'Sherwin-Williams',state:available,facts:[fact('Amount',48736),fact('Items','Painting supplies')],links:[{recordType:'JOURNAL_ENTRY',recordId:state.attempt.entries.find(entry=>entry.source?.kind==='CARD_PURCHASE'&&entry.occurredOn==='2026-06-25')!.id,relationship:'Supports the single legitimate purchase'}],interpretation:'The attempt contains another unsupported duplicate.'},
    {id:'pressure-washer-receipt',type:'VENDOR_RECEIPT',title:'Fort Myers Equipment Rental — Equipment Receipt',date:'2026-06-08',issuer:'Fort Myers Equipment Rental',state:available,facts:[fact('Amount',680000),fact('Purchased item','Commercial pressure washer'),fact('Quantity',1)],links:[{recordType:'JOURNAL_ENTRY',recordId:findEntry(state,description=>description==='Commercial pressure washer'),relationship:'Supports equipment purchase'}],interpretation:'Supports capitalization to Tools & Equipment; depreciation is outside scope.'},
    {id:'cpa-entry-support',type:'CPA_SUPPORT',title:'Coastal Accounting & Tax — Year-End Entry Support',date:'2025-12-31',issuer:'Coastal Accounting & Tax',state:available,facts:[fact('Entry date','2025-12-31'),fact('Professional fee accrual',120000),fact('Prepared by','Coastal Accounting & Tax')],links:[{recordType:'JOURNAL_ENTRY',recordId:findEntry(state,description=>description.includes('year-end accrual')),relationship:'CPA-provided journal support'}],interpretation:'The historical entry is legitimate; that conclusion is not student-visible.'},
    {id:'unapplied-receipt',type:'CUSTOMER_RECEIPT',title:'Cape Premier Realty Customer Receipt — June 30',date:'2026-06-30',issuer:'Gulf Coast Community Bank',state:available,facts:[fact('Amount',75000),fact('Application status','Unapplied'),fact('Reference','CLIENT-ADVANCE-0630')],links:[{recordType:'PAYMENT',recordId:payment(state,'CLIENT-ADVANCE-0630').id,relationship:'Supports legitimate unapplied payment'}],interpretation:'The customer intends this for a future job; that purpose remains unavailable.'},
    {id:'payroll-report-june-14',type:'PAYROLL_PROVIDER_REPORT',title:'Gulf Coast Payroll Services — June 14 Payroll Report',date:'2026-06-14',issuer:'Gulf Coast Payroll Services',state:locked,facts:[fact('Payroll period start',suncoastPayrollTruth.payrollPeriod.from),fact('Payroll period end',suncoastPayrollTruth.payrollPeriod.through),fact('Pay date',suncoastPayrollTruth.payDate),fact('Gross wages',suncoastPayrollTruth.grossWagesCents),fact('Federal withholding',suncoastPayrollTruth.employeeFederalWithholdingCents),fact('State/local withholding',suncoastPayrollTruth.employeeStateLocalWithholdingCents),fact('Employee FICA',suncoastPayrollTruth.employeeFicaWithholdingCents),fact('Employer FICA',suncoastPayrollTruth.employerFicaExpenseCents),fact('Unemployment tax',suncoastPayrollTruth.employerUnemploymentTaxExpenseCents),fact('Net pay withdrawal',suncoastPayrollTruth.withdrawals.netPayCents),fact('Tax funding withdrawal',suncoastPayrollTruth.withdrawals.taxFundingCents),fact('Provider fee withdrawal',suncoastPayrollTruth.withdrawals.providerFeeCents)],links:state.attempt.entries.filter(entry=>entry.source?.kind==='P002_SIMPLIFIED_PAYROLL').map(entry=>({recordType:'JOURNAL_ENTRY' as const,recordId:entry.id,relationship:'Bank withdrawal associated with payroll cycle'})),interpretation:'Supports restoration of the P-001A payroll treatment.'},
    {id:'abc-deposit-agreement',type:'VENDOR_AGREEMENT',title:'ABC Trailer & Equipment — Deposit Agreement',date:'2026-06-17',issuer:'ABC Trailer & Equipment',state:locked,facts:[fact('Deposit paid',240000),fact('Purpose','Deposit toward enclosed work trailer'),fact('Treatment','Creditable toward final purchase')],links:[{recordType:'JOURNAL_ENTRY',recordId:findEntry(state,description=>description==='Enclosed trailer deposit'),relationship:'Supports vendor payment purpose'}],interpretation:'Supports Trailer Deposit asset classification.'},
    {id:'card-clarification-0624',type:'CLIENT_CLARIFICATION',title:'June 24 Card Activity Clarification',date:'2026-07-02',issuer:'Michael Carter',state:locked,facts:[fact('Transaction amount',28643),fact('Business purpose','None — personal purchase'),fact('Authorized bookkeeping treatment','Owner Draws')],links:[{recordType:'JOURNAL_ENTRY',recordId:state.attempt.entries.find(entry=>entry.id.endsWith('card-review-0624'))!.id,relationship:'Clarifies card activity'}],interpretation:'Protected client clarification authorizes Owner Draws.'},
    {id:'jenkins-collectibility-intent',type:'CLIENT_INTENT',title:'Jenkins Collection Intent',date:'2026-07-02',issuer:'Michael Carter',state:'UNAVAILABLE',facts:[fact('Intent','Continue collection; do not write off')],links:[{recordType:'INVOICE',recordId:invoice(state,'JEN-OPEN').id,relationship:'Client intent for receivable'}],interpretation:'Unavailable until later conversation phase.'},
    {id:'unapplied-future-intent',type:'CLIENT_INTENT',title:'Unapplied Payment Intent',date:'2026-07-02',issuer:'Michael Carter',state:'UNAVAILABLE',facts:[fact('Intent','Apply toward a future job')],links:[{recordType:'PAYMENT',recordId:payment(state,'CLIENT-ADVANCE-0630').id,relationship:'Client intent for unapplied amount'}],interpretation:'Unavailable until later conversation phase.'},
    {id:'instructor-case-memo',type:'INSTRUCTOR_MEMO',title:'Suncoast Lab 1 Instructor Evidence Map',date:'2026-07-01',issuer:'Practice Lab',state:'INSTRUCTOR_ONLY',facts:[fact('Scope','Protected evidence interpretations and scenario mapping')],links:[],interpretation:'Instructor-only control document.'},
  ];return Object.freeze(documents.map(freezeDocument));}

const unlockRules:readonly UnlockRule[]=Object.freeze([
  {documentId:'payroll-report-june-14',authorization:'DOCUMENT_REQUESTED',requestSubject:'payroll support'},
  {documentId:'abc-deposit-agreement',authorization:'DOCUMENT_REQUESTED',requestSubject:'ABC transaction support'},
  {documentId:'card-clarification-0624',authorization:'CLIENT_CLARIFICATION_COMPLETED',requestSubject:'June 24 card activity'},
]);
const addAudit=(value:SuncoastEvidenceAttempt,event:Omit<EvidenceAuditEvent,'sequence'|'at'>):SuncoastEvidenceAttempt=>{const next=Object.freeze({sequence:value.audit.length+1,at:`2026-07-03T09:${String(value.audit.length).padStart(2,'0')}:00.000Z`,...event});return{...value,audit:Object.freeze([...value.audit,next])}};

export async function deriveSuncoastEvidence(studentId:string,attemptId:string,generation=1):Promise<SuncoastEvidenceAttempt>{const p002=await deriveP002StudentStart(studentId,attemptId,generation);return Object.freeze({attemptId,studentId,generation,documents:canonicalDocuments(p002),audit:Object.freeze([]),unlockRules,p002})}
export function evidenceStudentView(value:SuncoastEvidenceAttempt){const documents=value.documents.filter(document=>document.state==='AVAILABLE_AT_START'||document.state==='UNLOCKED').map(document=>({id:document.id,type:document.type,title:document.title,date:document.date,issuer:document.issuer,facts:document.facts,links:document.links,state:document.state}));return{attemptId:value.attemptId,generation:value.generation,documents,audit:value.audit.map(event=>({sequence:event.sequence,at:event.at,kind:event.kind,documentId:event.documentId,referenceId:event.referenceId}))}}
export function listEvidence(value:SuncoastEvidenceAttempt):SuncoastEvidenceAttempt{return addAudit(value,{kind:'DOCUMENT_LIST_VIEWED'})}
export function openEvidence(value:SuncoastEvidenceAttempt,documentId:string,download=false):SuncoastEvidenceAttempt{if(!evidenceStudentView(value).documents.some(document=>document.id===documentId))throw new InvalidReferenceError('Evidence unavailable');return addAudit(value,{kind:download?'DOCUMENT_DOWNLOADED':'DOCUMENT_OPENED',documentId})}
export function followEvidenceReference(value:SuncoastEvidenceAttempt,documentId:string,referenceId:string):SuncoastEvidenceAttempt{const document=evidenceStudentView(value).documents.find(item=>item.id===documentId);if(!document||!document.links.some(link=>link.recordId===referenceId))throw new InvalidReferenceError('Evidence unavailable');return addAudit(value,{kind:'REFERENCE_FOLLOWED',documentId,referenceId})}
export function requestEvidence(value:SuncoastEvidenceAttempt,requestSubject:string):SuncoastEvidenceAttempt{return addAudit(value,{kind:'DOCUMENT_REQUESTED',referenceId:requestSubject})}
export function authorizeEvidence(value:SuncoastEvidenceAttempt,documentId:string,authorization:UnlockRule['authorization']):SuncoastEvidenceAttempt{const rule=value.unlockRules.find(item=>item.documentId===documentId&&item.authorization===authorization),document=value.documents.find(item=>item.id===documentId);const requestSatisfied=authorization!=='DOCUMENT_REQUESTED'||value.audit.some(event=>event.kind==='DOCUMENT_REQUESTED'&&event.referenceId===rule?.requestSubject);if(!rule||!document||document.state!=='LOCKED_REQUESTABLE'||!requestSatisfied)throw new InvalidReferenceError('Evidence unavailable');const updated={...value,documents:Object.freeze(value.documents.map(item=>item.id===documentId?freezeDocument({...item,state:'UNLOCKED'}):item))};return addAudit(updated,{kind:'DOCUMENT_UNLOCKED',documentId})}
export async function resetSuncoastEvidence(value:SuncoastEvidenceAttempt,newAttemptId:string):Promise<{old:SuncoastEvidenceAttempt;next:SuncoastEvidenceAttempt}>{return{old:value,next:await deriveSuncoastEvidence(value.studentId,newAttemptId,value.generation+1)}}
