import { expect, it } from 'vitest';
import { StudentApi } from '../apps/api/application.js';
import { OperationalStudentApi, StudentBookkeepingCommandApi } from '../apps/api/application.js';
import { StudentBookkeepingCommandService, createStudentCommandSession, type StudentCommandSession } from '../packages/accounting-domain/src/suncoast-commands.js';
import { PracticeLabService, type LabStore } from '../packages/accounting-domain/src/service.js';
import type { CaseTemplate, StudentAttempt } from '../packages/accounting-domain/src/model.js';
import type { OperationalAttempt } from '../packages/accounting-domain/src/operations-model.js';
import { OperationalAccountingService, type OperationalStore } from '../packages/accounting-domain/src/operations.js';
it('API identity comes only from authenticated context and student output excludes secrets',async()=>{const template:CaseTemplate={id:'t',slug:'x',title:'X',scenario:{},accounts:[],documents:[]};const attempts=new Map<string,StudentAttempt>();const store:LabStore={findTemplate:async()=>template,findAttemptForStudent:async(id,s)=>attempts.get(id)?.studentId===s?attempts.get(id)!:null,saveAttempt:async a=>{attempts.set(a.id,a)}};const api=new StudentApi(new PracticeLabService(store,{id:()=>crypto.randomUUID(),now:()=>new Date().toISOString()}));const result=await api.start({studentId:'authenticated-student'},'t');expect(JSON.stringify(result)).not.toMatch(/instructor|answer|solution|grading|score/i);expect((attempts.get(result.id)!).studentId).toBe('authenticated-student')});
it('operational API hides foreign attempts and template provenance',async()=>{const attempt:StudentAttempt={id:'attempt',studentId:'alice',templateId:'template',generation:1,status:'ACTIVE',accounts:[],entries:[],actions:[],unlockedDocumentIds:[]};let state:OperationalAttempt={attempt,customers:[{id:'customer',attemptId:'attempt',sourceTemplateCustomerId:'hidden-source',name:'Fictional Customer',active:true}],invoices:[],payments:[],applications:[],deposits:[],reconciliations:[]};const store:OperationalStore={findForStudent:async(id,student)=>id===state.attempt.id&&student===state.attempt.studentId?state:null,save:async next=>{state=next}};const service=new OperationalAccountingService(store,{id:()=>crypto.randomUUID(),now:()=>new Date().toISOString()});const api=new OperationalStudentApi(service,store);expect(await api.view({studentId:'mallory'},'attempt')).toBeNull();const view=await api.view({studentId:'alice'},'attempt');expect(JSON.stringify(view)).not.toMatch(/hidden-source|sourceTemplate|instructor|solution|answer/i)});

it('command API derives ownership only from authenticated context and returns a safe view',async()=>{let session:StudentCommandSession=await createStudentCommandSession('alice','attempt');const store={findForStudent:async(id:string,student:string)=>id===session.attemptId&&student===session.studentId?session:null,save:async(next:StudentCommandSession)=>{session=next}};const api=new StudentBookkeepingCommandApi(new StudentBookkeepingCommandService(store));await expect(api.view({studentId:'mallory'},'attempt')).rejects.toThrow('Attempt not found');const view=await api.execute({studentId:'alice'},'attempt',{type:'REVIEW',targetId:session.coaching.interaction.evidence.p002.attempt.state.attempt.entries[0].id},{expectedRevision:0,idempotencyKey:'api-1',help:'INDEPENDENT'});expect(view.revision).toBe(1);expect(JSON.stringify(view)).not.toMatch(/clearedLineFingerprints|sourceTemplate|scenarioId|criticalHook|"before"|"after"|"receipts"/)});
