import { describe, expect, it } from 'vitest';
import { PracticeLabService, assertBalanced, balanceSheet, profitAndLoss, studentView, trialBalance, type LabStore } from '../packages/accounting-domain/src/service.js';
import { InvalidReferenceError, LedgerIntegrityError, NotFoundError } from '../packages/accounting-domain/src/errors.js';
import type { CaseTemplate, StudentAttempt } from '../packages/accounting-domain/src/model.js';
class Memory implements LabStore { templates=new Map<string,CaseTemplate>(); attempts=new Map<string,StudentAttempt>(); async findTemplate(id:string){return this.templates.get(id)??null} async findAttemptForStudent(id:string,s:string){const a=this.attempts.get(id);return a?.studentId===s?a:null} async saveAttempt(a:StudentAttempt){this.attempts.set(a.id,a)} }
const template:CaseTemplate={id:'t',slug:'proof',title:'Proof',scenario:{safe:true},accounts:[{id:'ta1',code:'1000',name:'Cash',kind:'ASSET'},{id:'ta2',code:'3000',name:'Equity',kind:'EQUITY'}],documents:[{id:'doc',title:'Next',unlockAfterAction:2}]};
function setup(){const store=new Memory();store.templates.set('t',template);let n=0;const service=new PracticeLabService(store,{id:()=>`id${++n}`,now:()=> '2026-08-15T00:00:00Z'});return{store,service}}
describe('P-000 approval gates',()=>{
 it('rejects unbalanced and malformed lines',()=>{expect(()=>assertBalanced([{attemptAccountId:'a',debitCents:100},{attemptAccountId:'b',creditCents:99}])).toThrow(LedgerIntegrityError);expect(()=>assertBalanced([{attemptAccountId:'a',debitCents:1.1},{attemptAccountId:'b',creditCents:1.1}])).toThrow(LedgerIntegrityError)});
 it('instantiates without mutating template',async()=>{const{service}=setup();const before=JSON.stringify(template);await service.instantiate('alice','t');expect(JSON.stringify(template)).toBe(before)});
 it('fails closed across students',async()=>{const{service}=setup();const a=await service.instantiate('alice','t');await expect(service.reset('bob',a.id)).rejects.toBeInstanceOf(NotFoundError)});
 it('fails closed across attempts',async()=>{const{service}=setup();const a=await service.instantiate('alice','t');const b=await service.instantiate('alice','t');await expect(service.post('alice',a.id,{description:'x',occurredOn:'2026-08-15',lines:[{attemptAccountId:b.accounts[0].id,debitCents:100},{attemptAccountId:a.accounts[1].id,creditCents:100}]})).rejects.toBeInstanceOf(InvalidReferenceError)});
 it('derives reports from balanced lines and unlocks minimal proof',async()=>{const{service,store}=setup();const a=await service.instantiate('alice','t');await service.post('alice',a.id,{description:'Opening',occurredOn:'2026-08-15',lines:[{attemptAccountId:a.accounts[0].id,debitCents:100},{attemptAccountId:a.accounts[1].id,creditCents:100}]});const latest=store.attempts.get(a.id)!;expect(trialBalance(latest).map(x=>[x.debitCents,x.creditCents])).toEqual([[100,0],[0,100]]);expect(latest.unlockedDocumentIds).toContain('doc')});
 it('student serialization has no instructor vocabulary or indirect values',async()=>{const{service}=setup();const a=await service.instantiate('alice','t');const json=JSON.stringify(studentView(a));expect(json).not.toMatch(/solution|answer|instructor|private/i)});
 it('unlocked document serialization exposes identifiers but never source content',async()=>{const{service,store}=setup();const a=await service.instantiate('alice','t');await service.post('alice',a.id,{description:'Opening',occurredOn:'2026-08-17',lines:[{attemptAccountId:a.accounts[0].id,debitCents:100},{attemptAccountId:a.accounts[1].id,creditCents:100}]});const json=JSON.stringify(studentView(store.attempts.get(a.id)!));expect(json).toContain('doc');expect(json).not.toMatch(/content|answer|solution|instructor/i)});
 it('authorization errors do not reveal foreign attempt or template metadata',async()=>{const{service}=setup();const a=await service.instantiate('alice','t');await expect(service.reset('mallory',a.id)).rejects.toMatchObject({message:'Attempt not found',code:'NOT_FOUND'});});
 it('reset creates an empty new generation and preserves old history',async()=>{const{service,store}=setup();const a=await service.instantiate('alice','t');const next=await service.reset('alice',a.id);expect(next.generation).toBe(2);expect(next.entries).toEqual([]);expect(store.attempts.get(a.id)?.status).toBe('RESET')});
 it('derives P&L and Balance Sheet only from journal lines',()=>{const attempt:StudentAttempt={id:'a',studentId:'s',templateId:'t',generation:1,status:'ACTIVE',actions:[],unlockedDocumentIds:[],accounts:[{id:'cash',attemptId:'a',sourceTemplateAccountId:'1',code:'1000',name:'Cash',kind:'ASSET'},{id:'revenue',attemptId:'a',sourceTemplateAccountId:'2',code:'4000',name:'Revenue',kind:'REVENUE'}],entries:[{id:'e',attemptId:'a',description:'Sale',occurredOn:'2026-08-17',lines:[{id:'l1',entryId:'e',attemptAccountId:'cash',debitCents:500,creditCents:0},{id:'l2',entryId:'e',attemptAccountId:'revenue',debitCents:0,creditCents:500}]}]};expect(profitAndLoss(attempt).netIncomeCents).toBe(500);expect(balanceSheet(attempt).totalAssetsCents).toBe(500);expect(balanceSheet(attempt).totalLiabilitiesAndEquityCents).toBe(500)});
});
