import { describe, expect, it } from 'vitest';
import { InvalidReferenceError, InvalidStateError } from '../packages/accounting-domain/src/errors.js';
import type { AttemptAccount, StudentAttempt } from '../packages/accounting-domain/src/model.js';
import type { OperationalAttempt } from '../packages/accounting-domain/src/operations-model.js';
import { OperationalAccountingService, accountRegister, arAging, arControlDifference, customerBalances, initializeOperationalAttempt, invoiceDetails, operationalProfitAndLoss, operationalStudentView, reconciliationResult, type OperationalStore } from '../packages/accounting-domain/src/operations.js';
import { trialBalance } from '../packages/accounting-domain/src/service.js';

class Memory implements OperationalStore {
  states=new Map<string,OperationalAttempt>();
  async findForStudent(id:string,student:string){const state=this.states.get(id);return state?.attempt.studentId===student?state:null}
  async save(state:OperationalAttempt){this.states.set(state.attempt.id,state)}
}
const accounts:AttemptAccount[]=[
  {id:'bank',attemptId:'a',sourceTemplateAccountId:'t-bank',code:'1000',name:'Bank',kind:'ASSET',operationalRole:'BANK'},
  {id:'uf',attemptId:'a',sourceTemplateAccountId:'t-uf',code:'1010',name:'Undeposited Funds',kind:'ASSET',operationalRole:'UNDEPOSITED_FUNDS'},
  {id:'ar',attemptId:'a',sourceTemplateAccountId:'t-ar',code:'1100',name:'Accounts Receivable',kind:'ASSET',operationalRole:'ACCOUNTS_RECEIVABLE'},
  {id:'expense',attemptId:'a',sourceTemplateAccountId:'t-expense',code:'6000',name:'Supplies',kind:'EXPENSE'},
  {id:'revenue',attemptId:'a',sourceTemplateAccountId:'t-revenue',code:'4000',name:'Service Revenue',kind:'REVENUE'},
  {id:'revenue-2',attemptId:'a',sourceTemplateAccountId:'t-revenue-2',code:'4010',name:'Other Revenue',kind:'REVENUE'},
  {id:'card',attemptId:'a',sourceTemplateAccountId:'t-card',code:'2100',name:'Credit Card',kind:'LIABILITY',operationalRole:'CREDIT_CARD'},
];
function setup(){const store=new Memory();let n=0;const attempt:StudentAttempt={id:'a',studentId:'alice',templateId:'template',generation:1,status:'ACTIVE',accounts,entries:[],actions:[],unlockedDocumentIds:[]};store.states.set('a',{attempt,customers:[],invoices:[],payments:[],applications:[],deposits:[],reconciliations:[]});const service=new OperationalAccountingService(store,{id:()=>`id-${++n}`,now:()=>`2026-01-${String(n).padStart(2,'0')}T00:00:00Z`});return{store,service,state:()=>store.states.get('a')!}}
async function invoiceFlow(){const context=setup();const customer=await context.service.createCustomer('alice','a',{name:'Fictional Customer'});const invoice=await context.service.postInvoice('alice','a',{customerId:customer.id,number:'INV-1',invoiceDate:'2026-01-01',dueDate:'2026-01-31',arAccountId:'ar',lines:[{revenueAccountId:'revenue',description:'Service',amountCents:10000}]});return{...context,customer,invoice}}

describe('P-000A operational accounting',()=>{
  it('posts an invoice as balanced A/R and accrual revenue',async()=>{const{state}=await invoiceFlow();const current=state();expect(trialBalance(current.attempt).find(r=>r.accountId==='ar')?.debitCents).toBe(10000);expect(operationalProfitAndLoss(current,'ACCRUAL').netIncomeCents).toBe(10000);expect(operationalProfitAndLoss(current,'CASH').netIncomeCents).toBe(0)});
  it('supports partial application and derives customer and invoice balances',async()=>{const{service,state,customer,invoice}=await invoiceFlow();const payment=await service.receivePayment('alice','a',{customerId:customer.id,paymentDate:'2026-01-10',amountCents:6000,destinationAccountId:'uf',arAccountId:'ar'});await service.applyPayment('alice','a',payment.id,invoice.id,4000);expect(invoiceDetails(state())[0]).toMatchObject({amountCents:10000,appliedCents:4000,openCents:6000});expect(customerBalances(state())[0]).toMatchObject({invoiceOpenCents:6000,unappliedPaymentCents:2000,netReceivableCents:4000});expect(arControlDifference(state(),'ar')).toBe(0);expect(operationalProfitAndLoss(state(),'CASH').netIncomeCents).toBe(4000)});
  it('provides deterministic aging inputs and period-specific basis reporting',async()=>{const{service,state,customer,invoice}=await invoiceFlow();const payment=await service.receivePayment('alice','a',{customerId:customer.id,paymentDate:'2026-01-10',amountCents:1000,destinationAccountId:'uf',arAccountId:'ar'});await service.applyPayment('alice','a',payment.id,invoice.id,1000);expect(arAging(state(),'2026-02-10')[0]).toMatchObject({openCents:9000,daysPastDue:10});expect(operationalProfitAndLoss(state(),'ACCRUAL',{from:'2026-01-01',through:'2026-01-31'}).netIncomeCents).toBe(10000);expect(operationalProfitAndLoss(state(),'CASH',{from:'2026-02-01',through:'2026-02-28'}).netIncomeCents).toBe(0)});
  it('allows a legitimate unapplied payment',async()=>{const{service,state,customer}=await invoiceFlow();await service.receivePayment('alice','a',{customerId:customer.id,paymentDate:'2026-01-10',amountCents:2500,destinationAccountId:'uf',arAccountId:'ar'});expect(customerBalances(state())[0].unappliedPaymentCents).toBe(2500);expect(operationalProfitAndLoss(state(),'CASH').netIncomeCents).toBe(0)});
  it('rejects payment and invoice over-application',async()=>{const{service,customer,invoice}=await invoiceFlow();const payment=await service.receivePayment('alice','a',{customerId:customer.id,paymentDate:'2026-01-10',amountCents:6000,destinationAccountId:'uf',arAccountId:'ar'});await expect(service.applyPayment('alice','a',payment.id,invoice.id,6001)).rejects.toBeInstanceOf(InvalidStateError)});
  it('rejects wrong-customer and cross-attempt applications without disclosure',async()=>{const{service,customer,invoice}=await invoiceFlow();const other=await service.createCustomer('alice','a',{name:'Other'});const payment=await service.receivePayment('alice','a',{customerId:other.id,paymentDate:'2026-01-10',amountCents:1000,destinationAccountId:'uf',arAccountId:'ar'});await expect(service.applyPayment('alice','a',payment.id,invoice.id,1000)).rejects.toMatchObject({message:'Payment or invoice unavailable'});await expect(service.applyPayment('alice','a','foreign-payment',invoice.id,1000)).rejects.toBeInstanceOf(InvalidReferenceError);expect(customer.id).not.toBe(other.id)});
  it('moves Undeposited Funds to bank once without recognizing revenue again',async()=>{const{service,state,customer,invoice}=await invoiceFlow();const payment=await service.receivePayment('alice','a',{customerId:customer.id,paymentDate:'2026-01-10',amountCents:10000,destinationAccountId:'uf',arAccountId:'ar'});await service.applyPayment('alice','a',payment.id,invoice.id,10000);const before=operationalProfitAndLoss(state(),'CASH').netIncomeCents;await service.createDeposit('alice','a',{depositDate:'2026-01-11',bankAccountId:'bank',undepositedFundsAccountId:'uf',paymentIds:[payment.id]});expect(operationalProfitAndLoss(state(),'CASH').netIncomeCents).toBe(before);expect(trialBalance(state().attempt).find(r=>r.accountId==='uf')?.debitCents).toBe(0);await expect(service.createDeposit('alice','a',{depositDate:'2026-01-12',bankAccountId:'bank',undepositedFundsAccountId:'uf',paymentIds:[payment.id]})).rejects.toBeInstanceOf(InvalidReferenceError)});
  it('fails closed on cross-attempt deposit references',async()=>{const{service}=await invoiceFlow();await expect(service.createDeposit('alice','a',{depositDate:'2026-01-11',bankAccountId:'bank',undepositedFundsAccountId:'uf',paymentIds:['foreign']})).rejects.toBeInstanceOf(InvalidReferenceError)});
  it('detects A/R control divergence without a plug',async()=>{const{state}=await invoiceFlow();const current=state();const altered={...current,attempt:{...current.attempt,entries:[]}};expect(arControlDifference(altered,'ar')).toBe(-10000)});
  it('records card purchase and bank payment without duplicate expense',async()=>{const{service,state}=setup();await service.recordCardPurchase('alice','a',{date:'2026-01-05',cardAccountId:'card',purchaseAccountId:'expense',amountCents:1200});await service.payCreditCard('alice','a',{date:'2026-01-20',bankAccountId:'bank',cardAccountId:'card',amountCents:1200});expect(operationalProfitAndLoss(state(),'ACCRUAL').expenses.find(r=>r.accountId==='expense')?.amountCents).toBe(1200);expect(trialBalance(state().attempt).find(r=>r.accountId==='card')?.creditCents).toBe(0)});
  it('reconciles bank and card accounts and keeps BALANCED distinct from COMPLETED',async()=>{const{service,state}=setup();const purchase=await service.recordCardPurchase('alice','a',{date:'2026-01-05',cardAccountId:'card',purchaseAccountId:'expense',amountCents:1200});const payment=await service.payCreditCard('alice','a',{date:'2026-01-20',bankAccountId:'bank',cardAccountId:'card',amountCents:1200});const bankLine=payment.lines.find(l=>l.attemptAccountId==='bank')!;const bank=await service.startReconciliation('alice','a',{accountId:'bank',beginningDate:'2026-01-01',endingDate:'2026-01-31',beginningBalanceCents:5000,endingBalanceCents:3800,clearedJournalLineIds:[bankLine.id]});expect(bank.status).toBe('IN_PROGRESS');expect(reconciliationResult(state(),bank)).toMatchObject({balanced:true,historicalIntegrity:true});expect((await service.completeReconciliation('alice','a',bank.id)).status).toBe('COMPLETED');const cardLines=[purchase,payment].flatMap(e=>e.lines).filter(l=>l.attemptAccountId==='card').map(l=>l.id);const card=await service.startReconciliation('alice','a',{accountId:'card',beginningDate:'2026-01-01',endingDate:'2026-01-31',beginningBalanceCents:0,endingBalanceCents:0,clearedJournalLineIds:cardLines});expect(reconciliationResult(state(),card).balanced).toBe(true)});
  it('leaves legitimate outstanding lines uncleared and rejects non-zero close',async()=>{const{service,state}=setup();const payment=await service.payCreditCard('alice','a',{date:'2026-01-20',bankAccountId:'bank',cardAccountId:'card',amountCents:1200});const reconciliation=await service.startReconciliation('alice','a',{accountId:'bank',beginningDate:'2026-01-01',endingDate:'2026-01-31',beginningBalanceCents:5000,endingBalanceCents:5000,clearedJournalLineIds:[]});expect(accountRegister(state(),'bank')).toHaveLength(1);expect(payment.lines[1].creditCents).toBe(1200);await expect(service.completeReconciliation('alice','a',reconciliation.id)).resolves.toMatchObject({status:'COMPLETED'});const invalid=await service.startReconciliation('alice','a',{accountId:'bank',beginningDate:'2026-02-01',endingDate:'2026-02-28',beginningBalanceCents:5000,endingBalanceCents:4900,clearedJournalLineIds:[]});await expect(service.completeReconciliation('alice','a',invalid.id)).rejects.toBeInstanceOf(InvalidStateError)});
  it('detects a changed previously reconciled line',async()=>{const{service,state}=setup();const entry=await service.payCreditCard('alice','a',{date:'2026-01-20',bankAccountId:'bank',cardAccountId:'card',amountCents:1200});const line=entry.lines.find(l=>l.attemptAccountId==='bank')!;const reconciliation=await service.startReconciliation('alice','a',{accountId:'bank',beginningDate:'2026-01-01',endingDate:'2026-01-31',beginningBalanceCents:5000,endingBalanceCents:3800,clearedJournalLineIds:[line.id]});const current=state();const changed={...current,attempt:{...current.attempt,entries:current.attempt.entries.map(e=>e.id===entry.id?{...e,lines:e.lines.map(l=>l.id===line.id?{...l,creditCents:1100}:l)}:e)}};expect(reconciliationResult(changed,reconciliation).historicalIntegrity).toBe(false)});
  it('fails closed when an attempt-owned account has the wrong operational role',async()=>{const{service,customer}=await invoiceFlow();await expect(service.receivePayment('alice','a',{customerId:customer.id,paymentDate:'2026-01-10',amountCents:100,destinationAccountId:'ar',arAccountId:'ar'})).rejects.toBeInstanceOf(InvalidReferenceError);await expect(service.payCreditCard('alice','a',{date:'2026-01-20',bankAccountId:'uf',cardAccountId:'card',amountCents:100})).rejects.toBeInstanceOf(InvalidReferenceError);await expect(service.startReconciliation('alice','a',{accountId:'ar',beginningDate:'2026-01-01',endingDate:'2026-01-31',beginningBalanceCents:0,endingBalanceCents:0,clearedJournalLineIds:[]})).rejects.toBeInstanceOf(InvalidReferenceError)});
  it('allocates multi-line cash revenue cumulatively regardless of receipt splitting',async()=>{const{service,state}=setup();const customer=await service.createCustomer('alice','a',{name:'Fictional Customer'});const invoice=await service.postInvoice('alice','a',{customerId:customer.id,number:'ROUNDING',invoiceDate:'2026-01-01',dueDate:'2026-01-31',arAccountId:'ar',lines:[{revenueAccountId:'revenue',description:'One third',amountCents:1},{revenueAccountId:'revenue-2',description:'Two thirds',amountCents:2}]});for(let index=0;index<3;index++){const payment=await service.receivePayment('alice','a',{customerId:customer.id,paymentDate:`2026-01-${10+index}`,amountCents:1,destinationAccountId:'uf',arAccountId:'ar'});await service.applyPayment('alice','a',payment.id,invoice.id,1)}const report=operationalProfitAndLoss(state(),'CASH');expect(report.revenue.find(row=>row.accountId==='revenue')?.amountCents).toBe(1);expect(report.revenue.find(row=>row.accountId==='revenue-2')?.amountCents).toBe(2)});
  it('keeps operational student serialization free of hidden instructor fields',async()=>{const{state}=await invoiceFlow();const json=JSON.stringify(operationalStudentView(state()));expect(json).not.toMatch(/instructor|solution|answer|grading|score|fingerprint/i)});
  it('initializes reset generations from template customers without carrying mutable history',()=>{const{state}=setup();let n=0;const next={...state().attempt,id:'next',generation:2,entries:[],actions:[]};const initialized=initializeOperationalAttempt(next,[{id:'template-customer',name:'Fictional Customer',active:true}],{id:()=>`reset-${++n}`,now:()=>''});expect(initialized.customers[0]).toMatchObject({attemptId:'next',sourceTemplateCustomerId:'template-customer'});expect(initialized.invoices).toEqual([]);expect(initialized.payments).toEqual([])});
});
