import { describe, expect, it } from 'vitest';
import { InvalidReferenceError } from '../packages/accounting-domain/src/errors.js';
import { authorizeEvidence, deriveSuncoastEvidence, evidenceStudentView, followEvidenceReference, listEvidence, openEvidence, requestEvidence, resetSuncoastEvidence } from '../packages/accounting-domain/src/suncoast-evidence.js';
import { p002FinancialSnapshot } from '../packages/accounting-domain/src/suncoast-student-start.js';

const document=(value:ReturnType<typeof evidenceStudentView>,id:string)=>value.documents.find(item=>item.id===id)!;
const facts=(value:ReturnType<typeof evidenceStudentView>,id:string)=>Object.fromEntries(document(value,id).facts.map(fact=>[fact.label,fact.value]));

describe('P-003 Suncoast client evidence and document system',()=>{
  it('publishes the exact deterministic Day 1 inventory without inventory metadata or protected interpretations',async()=>{const value=await deriveSuncoastEvidence('student-a','attempt-a'),view=evidenceStudentView(value);expect(view.documents).toHaveLength(23);expect(view.documents.map(item=>item.id)).toEqual(['client-profile','checking-2026-04','checking-2026-05','checking-2026-06','visa-2026-04','visa-2026-05','visa-2026-06','vehicle-loan-june','martinez-invoice','martinez-remittance','reynolds-invoice-a','reynolds-invoice-b','reynolds-remittance','jenkins-invoice','palm-invoice','palm-remittance','palm-deposit','home-depot-jenkins','home-depot-palm','sherwin-receipt','pressure-washer-receipt','cpa-entry-support','unapplied-receipt']);const serialized=JSON.stringify(view);expect(serialized).not.toMatch(/LOCKED_REQUESTABLE|UNAVAILABLE|INSTRUCTOR_ONLY|interpretation|unlockRules|totalDocument|scenario|SUN-L1-|expected resolution|critical/i)});
  it('uses independent April through June statement truth rather than computed ledger balances',async()=>{const value=await deriveSuncoastEvidence('student-a','attempt-a'),view=evidenceStudentView(value);expect(['checking-2026-04','checking-2026-05','checking-2026-06'].map(id=>facts(view,id))).toEqual([expect.objectContaining({'Beginning balance':2845000,'Ending balance':4441000}),expect.objectContaining({'Beginning balance':4441000,'Ending balance':6992500}),expect.objectContaining({'Beginning balance':6992500,'Ending balance':8442200})]);expect(['visa-2026-04','visa-2026-05','visa-2026-06'].map(id=>facts(view,id))).toEqual([expect.objectContaining({'Beginning balance':485000,'Ending balance':545000}),expect.objectContaining({'Beginning balance':545000,'Ending balance':575000}),expect.objectContaining({'Beginning balance':575000,'Ending balance':430815,'June 24 transaction':28643})]);expect(p002FinancialSnapshot(value.p002).checking.calculatedClearedBalanceCents).not.toBe(8442200);expect(p002FinancialSnapshot(value.p002).visa.calculatedClearedBalanceCents).not.toBe(-430815)});
  it('provides the required loan, customer, vendor, equipment, CPA, and unapplied evidence with attempt-owned links',async()=>{const value=await deriveSuncoastEvidence('student-a','attempt-a'),view=evidenceStudentView(value);expect(facts(view,'vehicle-loan-june')).toMatchObject({'June payment':92500,Principal:69000,Interest:23500,'Ending principal balance':2791000});expect(facts(view,'reynolds-remittance')).toMatchObject({Amount:185000,'Invoice reference':'REY-A'});expect(facts(view,'jenkins-invoice')).toMatchObject({Amount:142500,Status:'Unpaid'});expect(facts(view,'palm-remittance').Amount).toBe(950000);expect(facts(view,'pressure-washer-receipt')).toMatchObject({Amount:680000,'Purchased item':'Commercial pressure washer'});expect(view.documents.filter(item=>item.issuer==='Home Depot')).toHaveLength(2);expect(new Set(view.documents.filter(item=>item.issuer==='Home Depot').flatMap(item=>item.links.map(link=>link.recordId))).size).toBe(2);expect(view.documents.filter(item=>item.issuer==='Sherwin-Williams')).toHaveLength(1);expect(view.documents.every(item=>item.links.every(link=>link.recordType==='STATEMENT_TRUTH'||link.recordId.includes('attempt-a')))).toBe(true)});
  it('keeps payroll, ABC purpose, and personal-card facts hidden until their distinct authorized event flows complete',async()=>{let value=await deriveSuncoastEvidence('student-a','attempt-a');expect(JSON.stringify(evidenceStudentView(value))).not.toMatch(/Gross wages|enclosed work trailer|Owner Draws|personal purchase/i);expect(()=>authorizeEvidence(value,'payroll-report-june-14','DOCUMENT_REQUESTED')).toThrow(InvalidReferenceError);value=requestEvidence(value,'payroll support');value=authorizeEvidence(value,'payroll-report-june-14','DOCUMENT_REQUESTED');expect(facts(evidenceStudentView(value),'payroll-report-june-14')).toMatchObject({'Gross wages':980000,'Federal withholding':105000,'Employee FICA':74970,'Employer FICA':74970,'Unemployment tax':15030,'Net pay withdrawal':800030,'Tax funding withdrawal':269970,'Provider fee withdrawal':10000});value=requestEvidence(value,'ABC transaction support');value=authorizeEvidence(value,'abc-deposit-agreement','DOCUMENT_REQUESTED');expect(facts(evidenceStudentView(value),'abc-deposit-agreement')).toMatchObject({'Deposit paid':240000,Purpose:'Deposit toward enclosed work trailer'});expect(()=>authorizeEvidence(value,'card-clarification-0624','DOCUMENT_REQUESTED')).toThrow(InvalidReferenceError);value=authorizeEvidence(value,'card-clarification-0624','CLIENT_CLARIFICATION_COMPLETED');expect(facts(evidenceStudentView(value),'card-clarification-0624')).toMatchObject({'Transaction amount':28643,'Business purpose':'None — personal purchase','Authorized bookkeeping treatment':'Owner Draws'})});
  it('never exposes unavailable intent or instructor controls and returns the same generic error for hidden and unknown IDs',async()=>{const value=await deriveSuncoastEvidence('student-a','attempt-a'),view=JSON.stringify(evidenceStudentView(value));expect(view).not.toMatch(/jenkins-collectibility-intent|unapplied-future-intent|instructor-case-memo|Continue collection|future job|Protected evidence/i);for(const id of ['jenkins-collectibility-intent','instructor-case-memo','unknown'])expect(()=>openEvidence(value,id)).toThrowError('Evidence unavailable');expect(()=>authorizeEvidence(value,'jenkins-collectibility-intent','SYSTEM_ACTION')).toThrowError('Evidence unavailable')});
  it('records list, open, download, request, unlock, and reference navigation as immutable append-only events',async()=>{let value=await deriveSuncoastEvidence('student-a','attempt-a');const original=value;value=listEvidence(value);value=openEvidence(value,'martinez-invoice');value=openEvidence(value,'martinez-invoice',true);value=followEvidenceReference(value,'martinez-invoice',document(evidenceStudentView(value),'martinez-invoice').links[0].recordId);value=requestEvidence(value,'payroll support');value=authorizeEvidence(value,'payroll-report-june-14','DOCUMENT_REQUESTED');expect(value.audit.map(event=>event.kind)).toEqual(['DOCUMENT_LIST_VIEWED','DOCUMENT_OPENED','DOCUMENT_DOWNLOADED','REFERENCE_FOLLOWED','DOCUMENT_REQUESTED','DOCUMENT_UNLOCKED']);expect(value.audit.map(event=>event.sequence)).toEqual([1,2,3,4,5,6]);expect(original.audit).toHaveLength(0);expect(Object.isFrozen(value.audit)).toBe(true);expect(()=>followEvidenceReference(value,'martinez-invoice','attempt-b-entry')).toThrowError('Evidence unavailable')});
  it('isolates attempts and reset creates a fresh locked generation without changing history or accounting truth',async()=>{let first=await deriveSuncoastEvidence('student-a','attempt-a');const other=await deriveSuncoastEvidence('student-b','attempt-b');first=requestEvidence(first,'payroll support');first=authorizeEvidence(first,'payroll-report-june-14','DOCUMENT_REQUESTED');expect(evidenceStudentView(first).documents).toHaveLength(24);expect(evidenceStudentView(other).documents).toHaveLength(23);const before=p002FinancialSnapshot(first.p002),{old,next}=await resetSuncoastEvidence(first,'attempt-reset'),after=p002FinancialSnapshot(next.p002);expect(old).toBe(first);expect(old.audit).toHaveLength(2);expect(next).toMatchObject({studentId:'student-a',attemptId:'attempt-reset',generation:2});expect(evidenceStudentView(next).documents).toHaveLength(23);expect(next.audit).toHaveLength(0);expect(after.cashJune.netIncomeCents).toBe(before.cashJune.netIncomeCents);expect(after.accrualJune.netIncomeCents).toBe(before.accrualJune.netIncomeCents);expect(after.balanceSheet.totalAssetsCents).toBe(before.balanceSheet.totalAssetsCents);expect(after.checking).toEqual(before.checking);expect(after.visa).toEqual(before.visa);expect(next.documents.flatMap(item=>item.links).filter(link=>link.recordType!=='STATEMENT_TRUTH').every(link=>link.recordId.includes('attempt-reset'))).toBe(true)});
});
