import { describe, expect, it } from 'vitest';
import { operationalProfitAndLoss, operationalStudentView, reconciliationResult } from '../packages/accounting-domain/src/operations.js';
import { balanceSheet, studentView } from '../packages/accounting-domain/src/service.js';
import { buildSuncoastMasterCase, suncoastAuthoritativeStatements, suncoastCanonicalSummary, suncoastInstructorFacts } from '../packages/accounting-domain/src/suncoast-master.js';

const revenue=(report:Awaited<ReturnType<typeof suncoastCanonicalSummary>>['cash']['april'],name:string)=>report.revenue.find(row=>row.name===name)?.amountCents;

describe('P-001 Suncoast clean master',()=>{
  it('instantiates deterministically from the P-000A operational model',async()=>{const first=await buildSuncoastMasterCase(),second=await buildSuncoastMasterCase();expect(first).toEqual(second);expect(first.state.invoices).toHaveLength(17);expect(first.state.payments).toHaveLength(15);expect(first.state.applications).toHaveLength(15);expect(first.state.deposits).toHaveLength(15);expect(first.state.reconciliations).toHaveLength(2)});
  it('establishes the exact April 1 opening position',async()=>{const{openingBalanceSheet}=await suncoastCanonicalSummary();expect(openingBalanceSheet.totalAssetsCents).toBe(9770000);expect(openingBalanceSheet.totalLiabilitiesAndEquityCents).toBe(9770000);expect(openingBalanceSheet.assets.find(row=>row.name==='Operating Checking')?.amountCents).toBe(2845000);expect(openingBalanceSheet.assets.find(row=>row.name==='Accounts Receivable')?.amountCents).toBe(875000);expect(openingBalanceSheet.assets.find(row=>row.name==='Tools & Equipment')?.amountCents).toBe(1850000);expect(openingBalanceSheet.assets.find(row=>row.name==='Vehicles')?.amountCents).toBe(4200000);expect(openingBalanceSheet.liabilities.find(row=>row.name==='Gulf Coast Business Visa')?.amountCents).toBe(485000);expect(openingBalanceSheet.liabilities.find(row=>row.name==='Vehicle Loan Payable')?.amountCents).toBe(2860000);expect(openingBalanceSheet.equity.find(row=>row.name==='Historical / Opening Equity')?.amountCents).toBe(6425000)});
  it('produces the required monthly cash revenue by income category',async()=>{const{cash}=await suncoastCanonicalSummary();expect([revenue(cash.april,'Handyman Income'),revenue(cash.april,'Painting Income'),revenue(cash.april,'Pressure Washing Income')]).toEqual([1285000,1460000,625000]);expect([revenue(cash.may,'Handyman Income'),revenue(cash.may,'Painting Income'),revenue(cash.may,'Pressure Washing Income')]).toEqual([1440000,1725000,710000]);expect([revenue(cash.june,'Handyman Income'),revenue(cash.june,'Painting Income'),revenue(cash.june,'Pressure Washing Income')]).toEqual([1565000,1890000,845000]);expect(cash.april.revenue.reduce((sum,row)=>sum+row.amountCents,0)).toBe(3370000);expect(cash.may.revenue.reduce((sum,row)=>sum+row.amountCents,0)).toBe(3875000);expect(cash.june.revenue.reduce((sum,row)=>sum+row.amountCents,0)).toBe(4300000)});
  it('documents naturally derived accrual results without mutating the ledger',async()=>{const master=await buildSuncoastMasterCase(),before=structuredClone(master.state);const april=operationalProfitAndLoss(master.state,'ACCRUAL',{from:'2026-04-01',through:'2026-04-30'}),may=operationalProfitAndLoss(master.state,'ACCRUAL',{from:'2026-05-01',through:'2026-05-31'}),june=operationalProfitAndLoss(master.state,'ACCRUAL',{from:'2026-06-01',through:'2026-06-30'});expect([april.revenue.reduce((s,r)=>s+r.amountCents,0),may.revenue.reduce((s,r)=>s+r.amountCents,0),june.revenue.reduce((s,r)=>s+r.amountCents,0)]).toEqual([2495000,3875000,4670000]);expect(master.state).toEqual(before)});
  it('keeps owner capital, equipment, trailer deposit, and loan allocation correct',async()=>{const{master,cash}=await suncoastCanonicalSummary();expect(master.state.attempt.entries.find(entry=>entry.source?.kind==='OWNER_CONTRIBUTION')?.lines.map(line=>[line.debitCents,line.creditCents])).toEqual([[500000,0],[0,500000]]);expect(cash.may.revenue.reduce((sum,row)=>sum+row.amountCents,0)).toBe(3875000);expect(master.state.attempt.entries.find(entry=>entry.description==='Commercial pressure washer')?.lines[0]).toMatchObject({attemptAccountId:master.accountIds['Tools & Equipment'],debitCents:680000});expect(master.state.attempt.entries.find(entry=>entry.description==='Enclosed trailer deposit')?.lines[0]).toMatchObject({attemptAccountId:master.accountIds['Trailer Deposit'],debitCents:240000});const loan=master.state.attempt.entries.find(entry=>entry.description==='Vehicle loan payment')!;expect(loan.lines.find(line=>line.attemptAccountId===master.accountIds['Vehicle Loan Payable'])?.debitCents).toBe(69000);expect(loan.lines.find(line=>line.attemptAccountId===master.accountIds['Interest Expense'])?.debitCents).toBe(23500);expect(loan.lines.find(line=>line.attemptAccountId===master.accountIds['Operating Checking'])?.creditCents).toBe(92500)});
  it('preserves exact independent vendor source identities',async()=>{const{master}=await suncoastCanonicalSummary();const homeDepot=master.sourceRecords.filter(record=>record.counterparty==='Home Depot'&&record.amountCents===64218),sherwin=master.sourceRecords.filter(record=>record.counterparty==='Sherwin-Williams'&&record.amountCents===48736);expect(homeDepot).toHaveLength(2);expect(new Set(homeDepot.map(record=>record.id)).size).toBe(2);expect(new Set(homeDepot.map(record=>record.entryId)).size).toBe(2);expect(sherwin).toHaveLength(1)});
  it('supports Palm Breeze and the complete Martinez lifecycle exactly once',async()=>{const{master}=await suncoastCanonicalSummary();const palm=master.state.payments.find(payment=>payment.reference==='RCPT-PALM-0626')!;expect(palm.amountCents).toBe(950000);expect(master.state.applications.find(application=>application.paymentId===palm.id)?.amountCents).toBe(950000);const martinez=master.state.payments.find(payment=>payment.reference==='RCPT-MARTINEZ-0612')!;expect(martinez.amountCents).toBe(385000);expect(master.state.applications.filter(application=>application.paymentId===martinez.id)).toHaveLength(1);expect(master.state.deposits.filter(deposit=>deposit.paymentIds.includes(martinez.id))).toHaveLength(1);expect(master.state.invoices.find(invoice=>invoice.id===master.state.applications.find(application=>application.paymentId===martinez.id)?.invoiceId)?.status).toBe('PAID')});
  it('applies Reynolds correctly and leaves Jenkins collectible',async()=>{const{ar,master}=await suncoastCanonicalSummary();const reynolds=ar.details.find(detail=>detail.customerId===master.customerIds['David Reynolds']),jenkins=ar.details.find(detail=>detail.customerId===master.customerIds['Robert Jenkins']);expect(reynolds).toMatchObject({amountCents:227500,appliedCents:0,openCents:227500});expect(jenkins).toMatchObject({amountCents:142500,appliedCents:0,openCents:142500});const paidReynolds=master.state.invoices.find(invoice=>invoice.number==='REY-A')!;expect(master.state.applications.find(application=>application.invoiceId===paidReynolds.id)?.amountCents).toBe(185000);expect(ar.controlDifferenceCents).toBe(0)});
  it('has zero Undeposited Funds and exact A/R control at June 30',async()=>{const{trialBalance,ar,master}=await suncoastCanonicalSummary();expect(trialBalance.find(row=>row.accountId===master.accountIds['Undeposited Funds'])).toMatchObject({debitCents:0,creditCents:0});expect(trialBalance.find(row=>row.accountId===master.accountIds['Accounts Receivable'])?.debitCents).toBe(370000);expect(ar.details.reduce((sum,row)=>sum+row.openCents,0)).toBe(370000);expect(ar.controlDifferenceCents).toBe(0)});
  it('records card purchases and payment without duplicating expense',async()=>{const{master}=await suncoastCanonicalSummary();const cardPurchaseTotal=master.state.attempt.entries.filter(entry=>entry.source?.kind==='CARD_PURCHASE').flatMap(entry=>entry.lines).filter(line=>line.attemptAccountId===master.accountIds['Materials & Supplies']||line.attemptAccountId===master.accountIds['Advertising & Marketing']||line.attemptAccountId===master.accountIds['Software & Subscriptions']).reduce((sum,line)=>sum+line.debitCents,0);expect(cardPurchaseTotal).toBe(267172);const cardPayment=master.state.attempt.entries.find(entry=>entry.source?.kind==='CARD_PAYMENT')!;expect(cardPayment.lines.some(line=>line.attemptAccountId===master.accountIds['Gulf Coast Business Visa']&&line.debitCents===350000)).toBe(true);expect(cardPayment.lines.some(line=>line.attemptAccountId===master.accountIds['Operating Checking']&&line.creditCents===350000)).toBe(true);expect(cardPayment.lines.every(line=>!['EXPENSE','REVENUE'].includes(master.state.attempt.accounts.find(account=>account.id===line.attemptAccountId)!.kind))).toBe(true)});
  it('reconciles checking and Visa to independent authoritative statement truth without adjustments',async()=>{const{master}=await suncoastCanonicalSummary();expect(master.checkingStatement).toMatchObject({...suncoastAuthoritativeStatements.checking,differenceCents:0});expect(master.cardStatement).toMatchObject({...suncoastAuthoritativeStatements.visa,differenceCents:0});for(const reconciliation of master.state.reconciliations){expect(reconciliation.status).toBe('COMPLETED');expect(reconciliationResult(master.state,reconciliation)).toMatchObject({balanced:true,historicalIntegrity:true,differenceCents:0});expect(reconciliationResult(master.state,{...reconciliation,endingBalanceCents:reconciliation.endingBalanceCents+1})).toMatchObject({balanced:false,differenceCents:1})}expect(master.state.attempt.entries.some(entry=>/plug|adjustment/i.test(entry.description))).toBe(false)});
  it('keeps every entry, Trial Balance, and ending Balance Sheet balanced',async()=>{const{master,trialBalance,endingBalanceSheet}=await suncoastCanonicalSummary();for(const entry of master.state.attempt.entries){expect(entry.lines.reduce((sum,line)=>sum+line.debitCents,0),entry.description).toBe(entry.lines.reduce((sum,line)=>sum+line.creditCents,0))}expect(trialBalance.reduce((sum,row)=>sum+row.debitCents,0)).toBe(trialBalance.reduce((sum,row)=>sum+row.creditCents,0));expect(endingBalanceSheet.totalAssetsCents).toBe(15807200);expect(endingBalanceSheet.totalAssetsCents).toBe(endingBalanceSheet.totalLiabilitiesAndEquityCents);expect(balanceSheet(master.state.attempt)).toEqual(endingBalanceSheet)});
  it('keeps instructor facts out of all student-facing serialization',async()=>{const master=await buildSuncoastMasterCase();const exposed=JSON.stringify({base:studentView(master.state.attempt),operations:operationalStudentView(master.state),metadata:master.studentMetadata});expect(exposed).not.toContain(suncoastInstructorFacts.trailerDeposit);expect(exposed).not.toContain(suncoastInstructorFacts.cpaEntry);expect(exposed).not.toMatch(/collectible|loan allocation|instructor|hidden answer|correct invoice/i)});
});
