import { describe, expect, it } from 'vitest';
import { operationalStudentView } from '../packages/accounting-domain/src/operations.js';
import { buildSuncoastMasterCase, suncoastCanonicalSummary, suncoastPayrollTruth } from '../packages/accounting-domain/src/suncoast-master.js';

describe('P-001A Suncoast payroll component truth',()=>{
  it('reconciles the provider report components exactly',()=>{const payroll=suncoastPayrollTruth;expect(payroll.grossWagesCents-payroll.employeeFederalWithholdingCents-payroll.employeeStateLocalWithholdingCents-payroll.employeeFicaWithholdingCents).toBe(payroll.netEmployeePayCents);expect(payroll.employerFicaExpenseCents+payroll.employerUnemploymentTaxExpenseCents).toBe(payroll.employerPayrollTaxExpenseCents);expect(payroll.employeeFederalWithholdingCents+payroll.employeeStateLocalWithholdingCents+payroll.employeeFicaWithholdingCents+payroll.employerPayrollTaxExpenseCents).toBe(payroll.totalPayrollLiabilitiesGeneratedCents);expect(payroll.withdrawals.netPayCents+payroll.withdrawals.taxFundingCents+payroll.withdrawals.providerFeeCents).toBe(payroll.withdrawals.totalCents);expect(payroll.withdrawals.netPayCents).toBe(payroll.netEmployeePayCents);expect(payroll.withdrawals.taxFundingCents).toBe(payroll.totalPayrollLiabilitiesGeneratedCents)});
  it('posts balanced wage recognition, tax remittance, and provider fee entries',async()=>{const master=await buildSuncoastMasterCase();const entries=master.state.attempt.entries.filter(entry=>entry.source?.kind.startsWith('PAYROLL_'));expect(entries).toHaveLength(3);for(const entry of entries)expect(entry.lines.reduce((sum,line)=>sum+line.debitCents-line.creditCents,0),entry.description).toBe(0);const recognition=entries.find(entry=>entry.source?.kind==='PAYROLL_CYCLE')!;expect(recognition.lines.find(line=>line.attemptAccountId===master.accountIds['Payroll Expense'])?.debitCents).toBe(980000);expect(recognition.lines.find(line=>line.attemptAccountId===master.accountIds['Employer Payroll Tax Expense'])?.debitCents).toBe(90000);expect(recognition.lines.find(line=>line.attemptAccountId===master.accountIds['Payroll Liabilities'])?.creditCents).toBe(269970);expect(recognition.lines.find(line=>line.attemptAccountId===master.accountIds['Operating Checking'])?.creditCents).toBe(800030)});
  it('clears supported payroll liabilities and matches all provider withdrawals',async()=>{const{master,trialBalance}=await suncoastCanonicalSummary();expect(trialBalance.find(row=>row.accountId===master.accountIds['Payroll Liabilities'])).toMatchObject({debitCents:0,creditCents:0});const checkingCredits=master.state.attempt.entries.filter(entry=>entry.occurredOn==='2026-06-14'&&entry.source?.kind.startsWith('PAYROLL_')).flatMap(entry=>entry.lines).filter(line=>line.attemptAccountId===master.accountIds['Operating Checking']).map(line=>line.creditCents).sort((a,b)=>a-b);expect(checkingCredits).toEqual([10000,269970,800030]);expect(checkingCredits.reduce((sum,value)=>sum+value,0)).toBe(suncoastPayrollTruth.withdrawals.totalCents)});
  it('updates June P&Ls and Balance Sheet naturally without duplicate payroll expense',async()=>{const{cash,accrual,endingBalanceSheet,master}=await suncoastCanonicalSummary();expect(cash.june.expenses.reduce((sum,row)=>sum+row.amountCents,0)).toBe(1763472);expect(cash.june.netIncomeCents).toBe(2536528);expect(accrual.june.expenses.reduce((sum,row)=>sum+row.amountCents,0)).toBe(1763472);expect(accrual.june.netIncomeCents).toBe(2906528);expect(cash.june.expenses.find(row=>row.name==='Payroll Expense')?.amountCents).toBe(980000);expect(cash.june.expenses.find(row=>row.name==='Employer Payroll Tax Expense')?.amountCents).toBe(90000);expect(cash.june.expenses.find(row=>row.name==='Professional Fees')?.amountCents).toBe(10000);expect(master.state.attempt.entries.filter(entry=>entry.occurredOn==='2026-06-14').flatMap(entry=>entry.lines).filter(line=>line.attemptAccountId===master.accountIds['Payroll Expense']).reduce((sum,line)=>sum+line.debitCents-line.creditCents,0)).toBe(980000);expect(endingBalanceSheet.totalAssetsCents).toBe(15707200);expect(endingBalanceSheet.currentEarningsCents).toBe(5589028)});
  it('preserves independent checking truth and zero-difference reconciliation',async()=>{const master=await buildSuncoastMasterCase();expect(master.checkingStatement).toMatchObject({beginningBalanceCents:6992500,endingBalanceCents:8367200,differenceCents:0});expect(master.state.attempt.entries.some(entry=>/plug|clearing adjustment/i.test(entry.description))).toBe(false)});
  it('keeps protected component facts out of student-facing operational data and document metadata',async()=>{const master=await buildSuncoastMasterCase();const exposed=JSON.stringify({operations:operationalStudentView(master.state),metadata:master.studentMetadata});expect(exposed).not.toMatch(/grossWagesCents|employeeFederalWithholdingCents|employeeFicaWithholdingCents|employerPayrollTaxExpenseCents|totalPayrollLiabilitiesGeneratedCents|netEmployeePayCents|withdrawals/i);expect(exposed).not.toMatch(/gross wages|employer fica|unemployment tax|payroll liabilities generated/i)});
});
