import { describe, expect, it } from 'vitest';
import { NotFoundError } from '../packages/accounting-domain/src/errors.js';
import { OperationalAccountingService, arControlDifference, reconciliationResult, type OperationalStore } from '../packages/accounting-domain/src/operations.js';
import { buildResolvedP002State, deriveP002StudentStart, p002FinancialSnapshot, p002ScenarioDefinitions, p002StudentView, recordP002Action, resetP002Attempt } from '../packages/accounting-domain/src/suncoast-student-start.js';

const account=(state:Awaited<ReturnType<typeof deriveP002StudentStart>>['attempt']['state'],name:string)=>state.attempt.accounts.find(value=>value.name===name)!;
const balance=(state:Awaited<ReturnType<typeof deriveP002StudentStart>>['attempt']['state'],name:string)=>state.attempt.entries.flatMap(entry=>entry.lines).filter(line=>line.attemptAccountId===account(state,name).id).reduce((sum,line)=>sum+line.debitCents-line.creditCents,0);
const normalized=(value:unknown,attemptId:string)=>{const result=JSON.parse(JSON.stringify(value).replaceAll(attemptId,'ATTEMPT'));if(result.attempt?.studentId)result.attempt.studentId='STUDENT';return result};

describe('P-002 Suncoast controlled student starting state',()=>{
  it('defines every SUN-L1-01 through SUN-L1-20 control exactly once and only in instructor state',async()=>{expect(p002ScenarioDefinitions.map(value=>value.id)).toEqual(Array.from({length:20},(_,index)=>`SUN-L1-${String(index+1).padStart(2,'0')}`));const value=await deriveP002StudentStart('student-a','attempt-a');expect(JSON.stringify(p002StudentView(value))).not.toMatch(/SUN-L1-|STARTING_ERROR|INVESTIGATION_CONTROL|PROFESSIONAL_JUDGMENT_CONTROL|UNRESOLVED_INFORMATION|RECONCILIATION_CONSEQUENCE/)});
  it('SUN-L1-01 adds one unsupported Sherwin-Williams duplicate while retaining the supported purchase',async()=>{const{attempt}=await deriveP002StudentStart('student-a','attempt-a');const rows=attempt.state.attempt.entries.filter(entry=>entry.occurredOn==='2026-06-25'&&entry.lines.some(line=>line.debitCents===48736));expect(rows).toHaveLength(2);expect(rows.filter(entry=>entry.source?.kind==='CARD_PURCHASE')).toHaveLength(1);expect(rows.filter(entry=>entry.source?.kind==='P002_UNSUPPORTED_DUPLICATE')).toHaveLength(1)});
  it('SUN-L1-02 retains both separately sourced legitimate Home Depot purchases',async()=>{const value=await deriveP002StudentStart('student-a','attempt-a');const source=value.cleanMaster.sourceRecords.filter(record=>record.counterparty==='Home Depot'&&record.amountCents===64218);expect(source).toHaveLength(2);expect(new Set(source.map(record=>record.id)).size).toBe(2);expect(value.attempt.state.attempt.entries.filter(entry=>entry.occurredOn==='2026-06-22'&&entry.source?.kind==='CARD_PURCHASE'&&entry.lines.some(line=>line.debitCents===64218))).toHaveLength(2)});
  it('SUN-L1-03 preserves the $5,000 bank deposit but misclassifies its credit to income',async()=>{const value=await deriveP002StudentStart('student-a','attempt-a'),entry=value.attempt.state.attempt.entries.find(item=>item.description==='Owner contribution')!;expect(entry.lines.find(line=>line.attemptAccountId===account(value.attempt.state,'Operating Checking').id)?.debitCents).toBe(500000);expect(entry.lines.find(line=>line.attemptAccountId===account(value.attempt.state,'Painting Income').id)?.creditCents).toBe(500000);expect(balance(value.attempt.state,'Owner Contributions')).toBe(0)});
  it('SUN-L1-04 records the $925 loan payment fully to Vehicle Expense',async()=>{const value=await deriveP002StudentStart('student-a','attempt-a'),entry=value.attempt.state.attempt.entries.find(item=>item.description==='Vehicle loan payment')!;expect(entry.lines).toEqual(expect.arrayContaining([expect.objectContaining({attemptAccountId:account(value.attempt.state,'Vehicle Expense').id,debitCents:92500}),expect.objectContaining({attemptAccountId:account(value.attempt.state,'Operating Checking').id,creditCents:92500})]));expect(balance(value.attempt.state,'Vehicle Loan Payable')).toBe(-2860000)});
  it('SUN-L1-05 expenses the $6,800 pressure washer without depreciation behavior',async()=>{const value=await deriveP002StudentStart('student-a','attempt-a'),entry=value.attempt.state.attempt.entries.find(item=>item.description==='Commercial pressure washer')!;expect(entry.lines[0]).toMatchObject({attemptAccountId:account(value.attempt.state,'Repairs & Maintenance').id,debitCents:680000});expect(balance(value.attempt.state,'Tools & Equipment')).toBe(1850000);expect(JSON.stringify(value.attempt.state)).not.toMatch(/depreciation/i)});
  it('SUN-L1-06 holds ABC in an attempt-only suspense asset and withholds its purpose',async()=>{const value=await deriveP002StudentStart('student-a','attempt-a'),entry=value.attempt.state.attempt.entries.find(item=>item.description==='Enclosed trailer deposit')!;expect(entry.lines[0]).toMatchObject({attemptAccountId:account(value.attempt.state,'Uncategorized / Ask My Accountant').id,debitCents:240000});expect(value.attempt.visibleDocuments.some(document=>document.id==='ABC-TRAILER-0617')).toBe(false);expect(JSON.stringify(p002StudentView(value))).not.toMatch(/trailer purpose|enclosed work trailer/i)});
  it('SUN-L1-07 leaves the Martinez receipt in Undeposited Funds and adds bank-side income',async()=>{const value=await deriveP002StudentStart('student-a','attempt-a'),payment=value.attempt.state.payments.find(item=>item.reference==='RCPT-MARTINEZ-0612')!;expect(value.attempt.state.deposits.some(deposit=>deposit.paymentIds.includes(payment.id))).toBe(false);expect(value.attempt.state.attempt.entries.some(entry=>entry.id.endsWith('martinez-bank-income'))).toBe(true);expect(p002FinancialSnapshot(value).undepositedFundsCents).toBe(385000)});
  it('SUN-L1-08 applies Reynolds payment to Invoice B and preserves total A/R control',async()=>{const value=await deriveP002StudentStart('student-a','attempt-a'),state=value.attempt.state,payment=state.payments.find(item=>item.reference==='RCPT-REYNOLDS-0615')!,invoiceA=state.invoices.find(item=>item.number==='REY-A')!,invoiceB=state.invoices.find(item=>item.number==='REY-B')!;expect(state.applications.find(item=>item.paymentId===payment.id)).toMatchObject({invoiceId:invoiceB.id,amountCents:185000});expect(invoiceA.status).toBe('OPEN');expect(arControlDifference(state,account(state,'Accounts Receivable').id)).toBe(0)});
  it('SUN-L1-09 leaves the supported $1,425 Jenkins receivable intact',async()=>{const value=await deriveP002StudentStart('student-a','attempt-a'),state=value.attempt.state,jenkins=state.customers.find(item=>item.name==='Robert Jenkins')!,invoice=state.invoices.find(item=>item.customerId===jenkins.id)!;expect(invoice.lineItems.reduce((sum,line)=>sum+line.amountCents,0)).toBe(142500);expect(invoice.status).toBe('OPEN')});
  it('SUN-L1-10 preserves the historical CPA entries byte-for-byte after ID normalization',async()=>{const value=await deriveP002StudentStart('student-a','attempt-a');const clean=value.cleanMaster.state.attempt.entries.filter(entry=>entry.occurredOn==='2025-12-31').map(entry=>({description:entry.description,occurredOn:entry.occurredOn,amounts:entry.lines.map(line=>[line.debitCents,line.creditCents])}));const student=value.attempt.state.attempt.entries.filter(entry=>entry.occurredOn==='2025-12-31').map(entry=>({description:entry.description,occurredOn:entry.occurredOn,amounts:entry.lines.map(line=>[line.debitCents,line.creditCents])}));expect(student).toEqual(clean)});
  it('SUN-L1-11 adds June rent bank activity rather than matching the existing transaction',async()=>{const value=await deriveP002StudentStart('student-a','attempt-a');expect(value.attempt.state.attempt.entries.filter(entry=>entry.occurredOn==='2026-06-02'&&entry.lines.some(line=>line.debitCents===250000))).toHaveLength(2)});
  it('SUN-L1-12 records the supported $5,550 deposit movement as Advertising expense',async()=>{const value=await deriveP002StudentStart('student-a','attempt-a'),state=value.attempt.state,payment=state.payments.find(item=>item.reference==='RCPT-PAINT-0628')!,deposit=state.deposits.find(item=>item.paymentIds.includes(payment.id))!,entry=state.attempt.entries.find(item=>item.id===deposit.journalEntryId)!;expect(entry.lines).toEqual(expect.arrayContaining([expect.objectContaining({attemptAccountId:account(state,'Advertising & Marketing').id,debitCents:555000}),expect.objectContaining({attemptAccountId:account(state,'Undeposited Funds').id,creditCents:555000})]))});
  it('SUN-L1-13 alters a reconciled $318 transaction to $381 and breaks its historical fingerprint',async()=>{const value=await deriveP002StudentStart('student-a','attempt-a'),state=value.attempt.state,entry=state.attempt.entries.find(item=>item.description.includes('Office Depot'))!;expect(entry.lines.map(line=>[line.debitCents,line.creditCents])).toEqual([[38100,0],[0,38100]]);const historical=state.reconciliations.find(item=>item.status==='COMPLETED'&&item.accountId===account(state,'Operating Checking').id)!;expect(reconciliationResult(state,historical).historicalIntegrity).toBe(false)});
  it('SUN-L1-14 creates protected personal Visa activity in suspense without leaking purpose',async()=>{const value=await deriveP002StudentStart('student-a','attempt-a'),entry=value.attempt.state.attempt.entries.find(item=>item.id.endsWith('card-review-0624'))!;expect(entry.lines).toEqual(expect.arrayContaining([expect.objectContaining({attemptAccountId:account(value.attempt.state,'Uncategorized / Ask My Accountant').id,debitCents:28643}),expect.objectContaining({attemptAccountId:account(value.attempt.state,'Gulf Coast Business Visa').id,creditCents:28643})]));expect(JSON.stringify(p002StudentView(value))).not.toMatch(/purchase is personal|pending client clarification|personal-card/i)});
  it('SUN-L1-15 expenses the existing $3,500 card payment and leaves Visa overstated',async()=>{const value=await deriveP002StudentStart('student-a','attempt-a'),state=value.attempt.state,entry=state.attempt.entries.find(item=>item.source?.kind==='CARD_PAYMENT')!;expect(entry.lines[0]).toMatchObject({attemptAccountId:account(state,'Bank Fees').id,debitCents:350000});expect(balance(state,'Gulf Coast Business Visa')).toBe(-829551)});
  it('SUN-L1-16 retains three exact payroll withdrawals while hiding their component meaning',async()=>{const value=await deriveP002StudentStart('student-a','attempt-a'),entries=value.attempt.state.attempt.entries.filter(entry=>entry.occurredOn==='2026-06-14'&&entry.source?.kind==='P002_SIMPLIFIED_PAYROLL');expect(entries).toHaveLength(3);expect(entries.map(entry=>entry.lines.find(line=>line.attemptAccountId===account(value.attempt.state,'Operating Checking').id)?.creditCents).sort((a,b)=>a!-b!)).toEqual([10000,269970,800030]);expect(entries.flatMap(entry=>entry.lines).filter(line=>line.attemptAccountId===account(value.attempt.state,'Payroll Expense').id).reduce((sum,line)=>sum+line.debitCents,0)).toBe(1080000);expect(JSON.stringify(p002StudentView(value))).not.toMatch(/grossWagesCents|employeeFederalWithholdingCents|employeeFicaWithholdingCents|employerPayrollTaxExpenseCents|totalPayrollLiabilitiesGeneratedCents|netEmployeePayCents|employer fica|unemployment tax|tax funding|net pay/i)});
  it('SUN-L1-17 adds only attempt-local redundant expense accounts',async()=>{const value=await deriveP002StudentStart('student-a','attempt-a'),names=value.attempt.state.attempt.accounts.map(item=>item.name);expect(names).toEqual(expect.arrayContaining(['Advertising','Advertising Expense','Marketing','Marketing & Advertising']));expect(value.cleanMaster.state.attempt.accounts.some(item=>['Advertising','Advertising Expense','Marketing','Marketing & Advertising'].includes(item.name))).toBe(false)});
  it('SUN-L1-18 adds a legitimate $750 unapplied receipt without A/R divergence',async()=>{const value=await deriveP002StudentStart('student-a','attempt-a'),state=value.attempt.state,payment=state.payments.find(item=>item.reference==='CLIENT-ADVANCE-0630')!;expect(payment.amountCents).toBe(75000);expect(state.applications.some(item=>item.paymentId===payment.id)).toBe(false);expect(arControlDifference(state,account(state,'Accounts Receivable').id)).toBe(0);expect(JSON.stringify(p002StudentView(value))).not.toMatch(/future job|future-job intention/i)});
  it('SUN-L1-19 preserves the full legitimate Palm Breeze $9,500 lifecycle',async()=>{const value=await deriveP002StudentStart('student-a','attempt-a'),state=value.attempt.state,payment=state.payments.find(item=>item.reference==='RCPT-PALM-0626')!;expect(payment.amountCents).toBe(950000);expect(state.applications.find(item=>item.paymentId===payment.id)?.amountCents).toBe(950000);expect(state.deposits.some(item=>item.paymentIds.includes(payment.id))).toBe(true)});
  it('SUN-L1-20 produces natural reconciliation differences and no adjustment/plug entry',async()=>{const value=await deriveP002StudentStart('student-a','attempt-a'),snapshot=p002FinancialSnapshot(value);expect(snapshot.checking).toMatchObject({differenceCents:811300,balanced:false});expect(snapshot.visa).toMatchObject({differenceCents:-398736,balanced:false});expect(value.attempt.state.attempt.entries.some(entry=>/plug|reconciliation adjustment/i.test(entry.description))).toBe(false)});

  it('records the natural instructor-only starting financial state',async()=>{const snapshot=p002FinancialSnapshot(await deriveP002StudentStart('student-a','attempt-a'));expect(snapshot.cashJune.netIncomeCents).toBe(962492);expect(snapshot.accrualJune.netIncomeCents).toBe(1332492);expect(snapshot.balanceSheet).toMatchObject({totalAssetsCents:14629543,totalLiabilitiesAndEquityCents:14629543});expect(snapshot.balanceSheet.assets.find(row=>row.name==='Operating Checking')?.amountCents).toBe(7630900);expect(snapshot.balanceSheet.liabilities.find(row=>row.name==='Gulf Coast Business Visa')?.amountCents).toBe(829551);expect(snapshot.ar.controlDifferenceCents).toBe(0);expect(snapshot.undepositedFundsCents).toBe(385000)});
  it('derives deterministically, isolates attempts, and leaves the clean master untouched',async()=>{const first=await deriveP002StudentStart('student-a','attempt-a'),repeat=await deriveP002StudentStart('student-a','attempt-a'),other=await deriveP002StudentStart('student-b','attempt-b');expect(first).toEqual(repeat);expect(normalized(first.attempt.state,'attempt-a')).toEqual(normalized(other.attempt.state,'attempt-b'));expect(first.attempt.state.attempt.id).not.toBe(other.attempt.state.attempt.id);expect(first.cleanMaster).toEqual(await (async()=>{const again=await deriveP002StudentStart('student-c','attempt-c');return again.cleanMaster})());expect(JSON.stringify(first.cleanMaster)).not.toContain('P002_')});
  it('rejects cross-student access to a P-002 attempt through the server-side operational boundary',async()=>{const first=await deriveP002StudentStart('student-a','attempt-a'),other=await deriveP002StudentStart('student-b','attempt-b');const states=new Map([[first.attempt.state.attempt.id,first.attempt.state],[other.attempt.state.attempt.id,other.attempt.state]]);const store:OperationalStore={findForStudent:async(id,student)=>{const state=states.get(id);return state?.attempt.studentId===student?state:null},save:async state=>{states.set(state.attempt.id,state)}};const service=new OperationalAccountingService(store,{id:()=>`unused`,now:()=>`2026-07-02T00:00:00.000Z`});await expect(service.payCreditCard('student-a','attempt-b',{date:'2026-07-02',bankAccountId:account(other.attempt.state,'Operating Checking').id,cardAccountId:account(other.attempt.state,'Gulf Coast Business Visa').id,amountCents:100})).rejects.toBeInstanceOf(NotFoundError);expect(states.get('attempt-b')).toEqual(other.attempt.state)});
  it('reset creates a fresh equivalent generation while preserving old state and audit history',async()=>{let value=await deriveP002StudentStart('student-a','attempt-a');value=recordP002Action(value,'TRANSACTION_REVIEWED','target-1');const{old,next}=await resetP002Attempt(value,'attempt-reset');expect(old.attempt.state.attempt.status).toBe('RESET');expect(old.attempt.auditTrail).toHaveLength(1);expect(next.attempt.state.attempt).toMatchObject({id:'attempt-reset',generation:2,status:'ACTIVE'});expect(normalized(value.attempt.state,'attempt-a')).toEqual(normalized({...next.attempt.state,attempt:{...next.attempt.state.attempt,generation:1,actions:[{sequence:1,kind:'ATTEMPT_CREATED',at:'2026-07-01T09:00:00.000Z',detail:{}}]}},'attempt-reset'))});
  it('captures required action and critical-evidence hooks without scoring or student leakage',async()=>{let value=await deriveP002StudentStart('student-a','attempt-a');const actions=['TRANSACTION_REVIEWED','ACCOUNT_CHANGED','TRANSACTION_CORRECTED','TRANSACTION_VOIDED','APPLICATION_CHANGED','DOCUMENT_REVIEWED','ISSUE_FLAGGED','HISTORICAL_TRANSACTION_ALTERED','RECONCILIATION_ACTIVITY','RECONCILIATION_ADJUSTMENT_ATTEMPTED','ACCOUNT_CONSOLIDATED','SELF_CORRECTION'] as const;for(const [index,action] of actions.entries())value=recordP002Action(value,action,`target-${index}`,index===9?{hook:'RECONCILIATION_ADJUSTMENT_FORCED'}:{});expect(value.attempt.auditTrail.map(event=>event.action)).toEqual(actions);expect(value.attempt.auditTrail[9].hook).toBe('RECONCILIATION_ADJUSTMENT_FORCED');expect(JSON.stringify(p002StudentView(value))).not.toMatch(/RECONCILIATION_ADJUSTMENT_FORCED|critical|score|expected resolution/i)});
  it('keeps all instructor structures, hidden facts, unlock conditions, and exact solutions out of student serialization',async()=>{const value=await deriveP002StudentStart('student-a','attempt-a'),exposed=JSON.stringify(p002StudentView(value));expect(exposed).not.toMatch(/scenario|classification|cleanTruth|startingCondition|accountingEffect|unavailableEvidence|validResolution|criticalActions|hiddenFacts|payrollSupport|trailerPurpose|personalCardPurpose|unappliedPurpose|unlockAfter|P002_/i);expect(exposed).not.toContain(JSON.stringify(value.scenarios));expect(exposed).not.toContain('The ABC payment is a deposit toward an enclosed work trailer.')});
  it('provides a supported resolution state that restores clean accounting plus legitimate new activity without plugs',async()=>{const state=await buildResolvedP002State('student-a','resolved-a');const current=state.reconciliations.filter(item=>item.id.includes('-current-')).map(item=>reconciliationResult(state,item));expect(current).toEqual([expect.objectContaining({differenceCents:0,balanced:true,historicalIntegrity:true}),expect.objectContaining({differenceCents:0,balanced:true,historicalIntegrity:true})]);expect(state.reconciliations.filter(item=>item.status==='COMPLETED').map(item=>reconciliationResult(state,item)).every(item=>item.historicalIntegrity)).toBe(true);expect(balance(state,'Payroll Liabilities')).toBe(0);expect(balance(state,'Undeposited Funds')).toBe(0);expect(balance(state,'Operating Checking')).toBe(8442200);expect(balance(state,'Gulf Coast Business Visa')).toBe(-430815);expect(state.attempt.entries.some(entry=>/plug|reconciliation adjustment/i.test(entry.description))).toBe(false)});
});
